// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// Service for the `changes` resource.
///
/// @Snippet(path: "changesQuickstart")
public final class ChangesClient: Clients.ChangesProtocol, Sendable {
  let inner: any Clients.ChangesStub

  /// Creates a new `ChangesClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ChangesStub = try Clients.ChangesTransport(options)
    inner = Clients.ChangesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ChangesLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Atomically updates the ResourceRecordSet collection. Note: While `dns.changes.create` is the baseline permission required to invoke this method, additional permissions are checked depending on the specific additions or deletions contained in the payload.
  ///
  /// @Snippet(path: "changes_create")
  public func create(
    request: ChangesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Change {
    try await self.inner.create(request: request, options: options)
  }

  /// Fetches the representation of an existing Change.
  ///
  /// @Snippet(path: "changes_get")
  public func `get`(
    request: ChangesClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Change {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Enumerates Changes to a ResourceRecordSet collection.
  ///
  /// @Snippet(path: "changes_list")
  public func list(
    request: ChangesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ChangesListResponse {
    try await self.inner.list(request: request, options: options)
  }

  /// Enumerates Changes to a ResourceRecordSet collection.
  ///
  /// @Snippet(path: "changes_list")
  public func list(
    byItem: ChangesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Change, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ChangesListResponse in
      var request = byItem
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }
}

extension Clients {
  /// A Swift protocol to mock `ChangesClient`.
  ///
  /// To mock `ChangesClient` change your functions to receive
  /// `some ChangesProtocol` or `any ChangesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ChangesProtocol {
    /// See `ChangesClient.create`.
    func create(request: ChangesClient.CreateRequest) async throws -> Change

    /// See `ChangesClient.create`.
    func create(
      project: Swift.String,
      managedZone: Swift.String,
      body: Change?,
    ) async throws -> Change

    /// See `ChangesClient.`get``.
    func `get`(request: ChangesClient.GetRequest) async throws -> Change

    /// See `ChangesClient.`get``.
    func `get`(
      project: Swift.String,
      managedZone: Swift.String,
      changeId: Swift.String,
    ) async throws -> Change

    /// See `ChangesClient.list`.
    func list(request: ChangesClient.ListRequest) async throws -> ChangesListResponse

    /// See `ChangesClient.list`.
    func list(
      byItem: ChangesClient.ListRequest
    ) throws -> any AsyncSequence<Change, Swift.Error>

    /// See `ChangesClient.list`.
    func list(
      project: Swift.String,
      managedZone: Swift.String,
    ) throws -> any AsyncSequence<Change, Swift.Error>

    /// See `ChangesClient.create`.
    func create(
      request: ChangesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Change

    /// See `ChangesClient.`get``.
    func `get`(
      request: ChangesClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Change

    /// See `ChangesClient.list`.
    func list(
      request: ChangesClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ChangesListResponse

    /// See `ChangesClient.list`.
    func list(
      byItem: ChangesClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Change, Swift.Error>
  }
}

// Default implementations
extension Clients.ChangesProtocol {
  public func create(request: ChangesClient.CreateRequest) async throws -> Change {
    try await self.create(request: request, options: .init())
  }

  public func create(
    request: ChangesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Change {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func create(
    project: Swift.String,
    managedZone: Swift.String,
    body: Change?,
  ) async throws -> Change {
    let request = ChangesClient.CreateRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.body = body
    }
    return try await self.create(request: request)
  }

  public func `get`(request: ChangesClient.GetRequest) async throws -> Change {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: ChangesClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Change {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func `get`(
    project: Swift.String,
    managedZone: Swift.String,
    changeId: Swift.String,
  ) async throws -> Change {
    let request = ChangesClient.GetRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.changeId = changeId
    }
    return try await self.`get`(request: request)
  }

  public func list(request: ChangesClient.ListRequest) async throws -> ChangesListResponse {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: ChangesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ChangesListResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func list(
    byItem: ChangesClient.ListRequest
  ) throws -> any AsyncSequence<Change, Swift.Error> {
    try self.list(byItem: byItem, options: .init())
  }

  public func list(
    byItem: ChangesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Change, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ChangesListResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func list(
    project: Swift.String,
    managedZone: Swift.String,
  ) throws -> any AsyncSequence<Change, Swift.Error> {
    let request = ChangesClient.ListRequest().with {
      $0.project = project
      $0.managedZone = managedZone
    }
    return try self.list(byItem: request)
  }
}
