// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

extension ChangesClient {
  /// Synthetic request message for the [create()][.changes.create] method.
  public struct CreateRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [create()][.changes.create] method.
    public var body: Change? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CreateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let project = CodingKeys(stringValue: "project")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "project",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      self.body = try container.decodeIfPresent(Change.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.project, forKey: .project)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.changes.createRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [get()][.changes.get] method.
  public struct GetRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The identifier of the requested change, from a previous ResourceRecordSetsChangeResponse.
    public var changeId: Swift.String = Swift.String()

    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GetRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GetRequest().with { $0.changeId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let changeId = CodingKeys(stringValue: "changeId")
      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let project = CodingKeys(stringValue: "project")

      static let _knownKeys: Set<Swift.String> = [
        "changeId",
        "clientOperationId",
        "managedZone",
        "project",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .changeId) {
        self.changeId = value
      }
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.changeId, forKey: .changeId)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.project, forKey: .project)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.changes.getRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [list()][.changes.list] method.
  public struct ListRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Optional. Maximum number of results to be returned. If unspecified, the server decides how many results to return.
    public var maxResults: Swift.Int32? = nil

    /// Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
    public var pageToken: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Sorting criterion. The only supported value is change sequence.
    public var sortBy: ChangesClient.ListRequest.SortBy? = nil

    /// Sorting order direction: 'ascending' or 'descending'.
    public var sortOrder: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListRequest().with { $0.managedZone = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let maxResults = CodingKeys(stringValue: "maxResults")
      static let pageToken = CodingKeys(stringValue: "pageToken")
      static let project = CodingKeys(stringValue: "project")
      static let sortBy = CodingKeys(stringValue: "sortBy")
      static let sortOrder = CodingKeys(stringValue: "sortOrder")

      static let _knownKeys: Set<Swift.String> = [
        "managedZone",
        "maxResults",
        "pageToken",
        "project",
        "sortBy",
        "sortOrder",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      self.maxResults = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxResults)
      self.pageToken = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      self.sortBy = try container.decodeIfPresent(
        ChangesClient.ListRequest.SortBy.self, forKey: .sortBy)
      self.sortOrder = try container.decodeIfPresent(Swift.String.self, forKey: .sortOrder)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encodeIfPresent(self.maxResults, forKey: .maxResults)
      try container.encodeIfPresent(self.pageToken, forKey: .pageToken)
      try container.encode(self.project, forKey: .project)
      try container.encodeIfPresent(self.sortBy, forKey: .sortBy)
      try container.encodeIfPresent(self.sortOrder, forKey: .sortOrder)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [sortBy][.changes.listRequest.sortBy] field.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SortBy: Codable, Equatable, Sendable {
      case changeSequence
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .changeSequence: return "changeSequence"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SortBy/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "changeSequence": self = .changeSequence
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .changeSequence: return try container.encode("changeSequence")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.changes.listRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
}
