// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Parameters for DnsKey key generation. Used for generating initial keys for a new ManagedZone and as default when adding a new DnsKey.
public struct DnsKeySpec: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// String mnemonic specifying the DNSSEC algorithm of this key.
  public var algorithm: DnsKeySpec.Algorithm? = nil

  /// Length of the keys in bits.
  public var keyLength: Swift.UInt32? = nil

  /// Specifies whether this is a key signing key (KSK) or a zone signing key (ZSK). Key signing keys have the Secure Entry Point flag set and, when active, are only used to sign resource record sets of type DNSKEY. Zone signing keys do not have the Secure Entry Point flag set and are used to sign all other types of resource record sets.
  public var keyType: DnsKeySpec.KeyType? = nil

  public var kind: Swift.String? = nil

  /// Initialize a new instance of `DnsKeySpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DnsKeySpec().with { $0.algorithm = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The enumerated type for the [algorithm][.DnsKeySpec.algorithm] field.
  public enum Algorithm: Codable, Equatable, Sendable {
    case rsasha1
    case rsasha256
    case rsasha512
    case ecdsap256Sha256
    case ecdsap384Sha384
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .rsasha1
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .rsasha1: return 0
      case .rsasha256: return 1
      case .rsasha512: return 2
      case .ecdsap256Sha256: return 3
      case .ecdsap384Sha384: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .rsasha1: return "rsasha1"
      case .rsasha256: return "rsasha256"
      case .rsasha512: return "rsasha512"
      case .ecdsap256Sha256: return "ecdsap256sha256"
      case .ecdsap384Sha384: return "ecdsap384sha384"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Algorithm/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "rsasha1": self = .rsasha1
      case "rsasha256": self = .rsasha256
      case "rsasha512": self = .rsasha512
      case "ecdsap256sha256": self = .ecdsap256Sha256
      case "ecdsap384sha384": self = .ecdsap384Sha384
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Algorithm/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .rsasha1
      case 1: self = .rsasha256
      case 2: self = .rsasha512
      case 3: self = .ecdsap256Sha256
      case 4: self = .ecdsap384Sha384
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .rsasha1: return try container.encode(0)
      case .rsasha256: return try container.encode(1)
      case .rsasha512: return try container.encode(2)
      case .ecdsap256Sha256: return try container.encode(3)
      case .ecdsap384Sha384: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The enumerated type for the [keyType][.DnsKeySpec.keyType] field.
  public enum KeyType: Codable, Equatable, Sendable {
    case keySigning
    case zoneSigning
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .keySigning
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .keySigning: return 0
      case .zoneSigning: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .keySigning: return "keySigning"
      case .zoneSigning: return "zoneSigning"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:KeyType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "keySigning": self = .keySigning
      case "zoneSigning": self = .zoneSigning
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:KeyType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .keySigning
      case 1: self = .zoneSigning
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .keySigning: return try container.encode(0)
      case .zoneSigning: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.DnsKeySpec"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
