// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Provides the configuration for logging a type of permissions. Example: { "audit_log_configs": [ { "log_type": "DATA_READ", "exempted_members": [ "user:jose@example.com" ] }, { "log_type": "DATA_WRITE" } ] } This enables 'DATA_READ' and 'DATA_WRITE' logging, while exempting jose@example.com from DATA_READ logging.
public struct GoogleIamV1AuditLogConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Specifies the identities that do not cause logging for this type of permission. Follows the same format of Binding.members.
  public var exemptedMembers: [Swift.String] = []

  /// The log type that this config enables.
  public var logType: GoogleIamV1AuditLogConfig.LogType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GoogleIamV1AuditLogConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoogleIamV1AuditLogConfig().with { $0.exemptedMembers = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let exemptedMembers = CodingKeys(stringValue: "exemptedMembers")
    static let logType = CodingKeys(stringValue: "logType")

    static let _knownKeys: Set<Swift.String> = [
      "exemptedMembers",
      "logType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .exemptedMembers) {
      self.exemptedMembers = value
    }
    self.logType = try container.decodeIfPresent(
      GoogleIamV1AuditLogConfig.LogType.self, forKey: .logType)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.exemptedMembers, forKey: .exemptedMembers)
    try container.encodeIfPresent(self.logType, forKey: .logType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The enumerated type for the [logType][.GoogleIamV1AuditLogConfig.logType] field.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum LogType: Codable, Equatable, Hashable, Sendable {
    /// Default case. Should never be this.
    case unspecified
    /// Admin reads. Example: CloudIAM getIamPolicy
    case adminRead
    /// Data writes. Example: CloudSQL Users create
    case dataWrite
    /// Data reads. Example: CloudSQL Users list
    case dataRead
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(Swift.String)

    /// Returns the string value (or name) associated with the enumeration.
    public var stringValue: Swift.String {
      switch self {
      case .unspecified: return "LOG_TYPE_UNSPECIFIED"
      case .adminRead: return "ADMIN_READ"
      case .dataWrite: return "DATA_WRITE"
      case .dataRead: return "DATA_READ"
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LogType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LOG_TYPE_UNSPECIFIED": self = .unspecified
      case "ADMIN_READ": self = .adminRead
      case "DATA_WRITE": self = .dataWrite
      case "DATA_READ": self = .dataRead
      default: self = .unknownStringValue(stringValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      let s = try container.decode(Swift.String.self)
      self.init(stringValue: s)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("LOG_TYPE_UNSPECIFIED")
      case .adminRead: return try container.encode("ADMIN_READ")
      case .dataWrite: return try container.encode("DATA_WRITE")
      case .dataRead: return try container.encode("DATA_READ")
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.GoogleIamV1AuditLogConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
