// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for the `locations` resource.
///
/// @Snippet(path: "locationsQuickstart")
public final class LocationsClient: Clients.LocationsProtocol, Sendable {
  let inner: any Clients.LocationsStub

  /// Creates a new `LocationsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.LocationsStub = try Clients.LocationsTransport(options)
    inner = Clients.LocationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LocationsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "locations_get")
  public func `get`(
    request: LocationsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> Location {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other project-specific locations enabled for the project. For gRPC and client library implementations, the resource name is passed as the `name` field. For direct service calls, the resource name is incorporated into the request path based on the specific service implementation and version.
  ///
  /// @Snippet(path: "locations_list")
  public func list(
    request: LocationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> ListLocationsResponse {
    try await self.inner.list(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LocationsClient`.
  ///
  /// To mock `LocationsClient` change your functions to receive
  /// `some LocationsProtocol` or `any LocationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LocationsProtocol: Sendable {
    /// See `LocationsClient.`get``.
    func `get`(
      request: LocationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> Location

    /// See `LocationsClient.list`.
    func list(
      request: LocationsClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> ListLocationsResponse
  }
}

// Default implementations
extension Clients.LocationsProtocol {
  public func `get`(request: LocationsClient.GetRequest) async throws -> Location {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: LocationsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func `get`(
    name: Swift.String,
  ) async throws -> Location {
    let request = LocationsClient.GetRequest().with {
      $0.name = name
    }
    return try await self.`get`(request: request)
  }

  public func list(request: LocationsClient.ListRequest) async throws -> ListLocationsResponse {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: LocationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listByItems(
    request: LocationsClient.ListRequest
  ) -> some AsyncSequence<Location, any Swift.Error> & Sendable {
    self.listByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other project-specific locations enabled for the project. For gRPC and client library implementations, the resource name is passed as the `name` field. For direct service calls, the resource name is incorporated into the request path based on the specific service implementation and version.
  ///
  /// @Snippet(path: "locations_list")
  public func listByItems(
    request: LocationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Location, any Swift.Error> & Sendable {
    let listRpc = { @Sendable (token: Swift.String) async throws -> ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listByItems(
    name: Swift.String,
  ) -> some AsyncSequence<Location, any Swift.Error> & Sendable {
    let request = LocationsClient.ListRequest().with {
      $0.name = name
    }
    return self.listByItems(request: request)
  }
}
