// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

extension ManagedZonesClient {
  /// Synthetic request message for the [create()][.managedZones.create] method.
  public struct CreateRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [create()][.managedZones.create] method.
    public var body: ManagedZone? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CreateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let project = CodingKeys(stringValue: "project")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "project",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      self.body = try container.decodeIfPresent(ManagedZone.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.project, forKey: .project)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.createRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [delete()][.managedZones.delete] method.
  public struct DeleteRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DeleteRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeleteRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let project = CodingKeys(stringValue: "project")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "project",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.project, forKey: .project)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.deleteRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [get()][.managedZones.get] method.
  public struct GetRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GetRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GetRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let project = CodingKeys(stringValue: "project")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "project",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.project, forKey: .project)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.getRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [getIamPolicy()][.managedZones.getIamPolicy] method.
  public struct GetIamPolicyRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// REQUIRED: The resource for which the policy is being requested. See [Resource names](https://cloud.google.com/apis/design/resource_names) for the appropriate value for this field.
    public var resource: Swift.String = Swift.String()

    /// Synthetic request body field for the [getIamPolicy()][.managedZones.getIamPolicy] method.
    public var body: GoogleIamV1GetIamPolicyRequest? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GetIamPolicyRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GetIamPolicyRequest().with { $0.resource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let resource = CodingKeys(stringValue: "resource")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "resource",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
        self.resource = value
      }
      self.body = try container.decodeIfPresent(GoogleIamV1GetIamPolicyRequest.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.resource, forKey: .resource)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.getIamPolicyRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [list()][.managedZones.list] method.
  public struct ListRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Restricts the list to return only zones with this domain name.
    public var dnsName: Swift.String? = nil

    /// Optional. Maximum number of results to be returned. If unspecified, the server decides how many results to return.
    public var maxResults: Swift.Int32? = nil

    /// Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
    public var pageToken: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListRequest().with { $0.dnsName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dnsName = CodingKeys(stringValue: "dnsName")
      static let maxResults = CodingKeys(stringValue: "maxResults")
      static let pageToken = CodingKeys(stringValue: "pageToken")
      static let project = CodingKeys(stringValue: "project")

      static let _knownKeys: Set<Swift.String> = [
        "dnsName",
        "maxResults",
        "pageToken",
        "project",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.dnsName = try container.decodeIfPresent(Swift.String.self, forKey: .dnsName)
      self.maxResults = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxResults)
      self.pageToken = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.dnsName, forKey: .dnsName)
      try container.encodeIfPresent(self.maxResults, forKey: .maxResults)
      try container.encodeIfPresent(self.pageToken, forKey: .pageToken)
      try container.encode(self.project, forKey: .project)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.listRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [patch()][.managedZones.patch] method.
  public struct PatchRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [patch()][.managedZones.patch] method.
    public var body: ManagedZone? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PatchRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PatchRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let project = CodingKeys(stringValue: "project")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "project",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      self.body = try container.decodeIfPresent(ManagedZone.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.project, forKey: .project)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.patchRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [setIamPolicy()][.managedZones.setIamPolicy] method.
  public struct SetIamPolicyRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// REQUIRED: The resource for which the policy is being specified. See [Resource names](https://cloud.google.com/apis/design/resource_names) for the appropriate value for this field.
    public var resource: Swift.String = Swift.String()

    /// Synthetic request body field for the [setIamPolicy()][.managedZones.setIamPolicy] method.
    public var body: GoogleIamV1SetIamPolicyRequest? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SetIamPolicyRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SetIamPolicyRequest().with { $0.resource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let resource = CodingKeys(stringValue: "resource")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "resource",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
        self.resource = value
      }
      self.body = try container.decodeIfPresent(GoogleIamV1SetIamPolicyRequest.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.resource, forKey: .resource)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.setIamPolicyRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [testIamPermissions()][.managedZones.testIamPermissions] method.
  public struct TestIamPermissionsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// REQUIRED: The resource for which the policy detail is being requested. See [Resource names](https://cloud.google.com/apis/design/resource_names) for the appropriate value for this field.
    public var resource: Swift.String = Swift.String()

    /// Synthetic request body field for the [testIamPermissions()][.managedZones.testIamPermissions] method.
    public var body: GoogleIamV1TestIamPermissionsRequest? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TestIamPermissionsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TestIamPermissionsRequest().with { $0.resource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let resource = CodingKeys(stringValue: "resource")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "resource",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
        self.resource = value
      }
      self.body = try container.decodeIfPresent(
        GoogleIamV1TestIamPermissionsRequest.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.resource, forKey: .resource)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.testIamPermissionsRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [update()][.managedZones.update] method.
  public struct UpdateRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [update()][.managedZones.update] method.
    public var body: ManagedZone? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UpdateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpdateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let project = CodingKeys(stringValue: "project")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "project",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      self.body = try container.decodeIfPresent(ManagedZone.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.project, forKey: .project)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZones.updateRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
}
