// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol ManagedZonesStub: Sendable {
    func create(
      request: ManagedZonesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ManagedZone

    func delete(
      request: ManagedZonesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func `get`(
      request: ManagedZonesClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ManagedZone

    func getIamPolicy(
      request: ManagedZonesClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1Policy

    func list(
      request: ManagedZonesClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ManagedZonesListResponse

    func patch(
      request: ManagedZonesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Operation

    func setIamPolicy(
      request: ManagedZonesClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1Policy

    func testIamPermissions(
      request: ManagedZonesClient.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1TestIamPermissionsResponse

    func update(
      request: ManagedZonesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Operation

    func getOperation(
      request: ManagedZoneOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Operation
  }
}
