// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct ManagedZoneDnsSecConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Specifies parameters for generating initial DnsKeys for this ManagedZone. Can only be changed while the state is OFF.
  public var defaultKeySpecs: [DnsKeySpec] = []

  public var kind: Swift.String? = nil

  /// Specifies the mechanism for authenticated denial-of-existence responses. Can only be changed while the state is OFF.
  public var nonExistence: ManagedZoneDnsSecConfig.NonExistence? = nil

  /// Specifies whether DNSSEC is enabled, and what mode it is in.
  public var state: ManagedZoneDnsSecConfig.State? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ManagedZoneDnsSecConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ManagedZoneDnsSecConfig().with { $0.defaultKeySpecs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let defaultKeySpecs = CodingKeys(stringValue: "defaultKeySpecs")
    static let kind = CodingKeys(stringValue: "kind")
    static let nonExistence = CodingKeys(stringValue: "nonExistence")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "defaultKeySpecs",
      "kind",
      "nonExistence",
      "state",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([DnsKeySpec].self, forKey: .defaultKeySpecs) {
      self.defaultKeySpecs = value
    }
    self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
    self.nonExistence = try container.decodeIfPresent(
      ManagedZoneDnsSecConfig.NonExistence.self, forKey: .nonExistence)
    self.state = try container.decodeIfPresent(ManagedZoneDnsSecConfig.State.self, forKey: .state)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.defaultKeySpecs, forKey: .defaultKeySpecs)
    try container.encodeIfPresent(self.kind, forKey: .kind)
    try container.encodeIfPresent(self.nonExistence, forKey: .nonExistence)
    try container.encodeIfPresent(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The enumerated type for the [nonExistence][.ManagedZoneDnsSecConfig.nonExistence] field.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum NonExistence: Codable, Equatable, Hashable, Sendable {
    /// Indicates that Cloud DNS will sign records in the managed zone according to RFC 4034 and respond with NSEC records for names that do not exist.
    case nsec
    /// Indicates that Cloud DNS will sign records in the managed zone according to RFC 5155 and respond with NSEC3 records for names that do not exist.
    case nsec3
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(Swift.String)

    /// Returns the string value (or name) associated with the enumeration.
    public var stringValue: Swift.String? {
      switch self {
      case .nsec: return "nsec"
      case .nsec3: return "nsec3"
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NonExistence/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "nsec": self = .nsec
      case "nsec3": self = .nsec3
      default: self = .unknownStringValue(stringValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      let s = try container.decode(Swift.String.self)
      self.init(stringValue: s)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .nsec: return try container.encode("nsec")
      case .nsec3: return try container.encode("nsec3")
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The enumerated type for the [state][.ManagedZoneDnsSecConfig.state] field.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// DNSSEC is disabled; the zone is not signed.
    case off
    /// DNSSEC is enabled; the zone is signed and fully managed.
    case on
    /// DNSSEC is enabled, but in a "transfer" mode.
    case transfer
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(Swift.String)

    /// Returns the string value (or name) associated with the enumeration.
    public var stringValue: Swift.String? {
      switch self {
      case .off: return "off"
      case .on: return "on"
      case .transfer: return "transfer"
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "off": self = .off
      case "on": self = .on
      case "transfer": self = .transfer
      default: self = .unknownStringValue(stringValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      let s = try container.decode(Swift.String.self)
      self.init(stringValue: s)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .off: return try container.encode("off")
      case .on: return try container.encode("on")
      case .transfer: return try container.encode("transfer")
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.ManagedZoneDnsSecConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
