// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for the `managedZoneOperations` resource.
///
/// @Snippet(path: "managedZoneOperationsQuickstart")
public final class ManagedZoneOperationsClient: Clients.ManagedZoneOperationsProtocol, Sendable {
  let inner: any Clients.ManagedZoneOperationsStub

  /// Creates a new `ManagedZoneOperationsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ManagedZoneOperationsStub = try Clients.ManagedZoneOperationsTransport(
      options)
    inner = Clients.ManagedZoneOperationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ManagedZoneOperationsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Fetches the representation of an existing Operation.
  ///
  /// @Snippet(path: "managedZoneOperations_get")
  public func `get`(
    request: ManagedZoneOperationsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> Operation {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Enumerates Operations for the given ManagedZone.
  ///
  /// @Snippet(path: "managedZoneOperations_list")
  public func list(
    request: ManagedZoneOperationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> ManagedZoneOperationsListResponse {
    try await self.inner.list(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ManagedZoneOperationsClient`.
  ///
  /// To mock `ManagedZoneOperationsClient` change your functions to receive
  /// `some ManagedZoneOperationsProtocol` or `any ManagedZoneOperationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ManagedZoneOperationsProtocol: Sendable {
    /// See `ManagedZoneOperationsClient.`get``.
    func `get`(
      request: ManagedZoneOperationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> Operation

    /// See `ManagedZoneOperationsClient.list`.
    func list(
      request: ManagedZoneOperationsClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> ManagedZoneOperationsListResponse
  }
}

// Default implementations
extension Clients.ManagedZoneOperationsProtocol {
  public func `get`(request: ManagedZoneOperationsClient.GetRequest) async throws -> Operation {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: ManagedZoneOperationsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func `get`(
    project: Swift.String,
    managedZone: Swift.String,
    operation: Swift.String,
  ) async throws -> Operation {
    let request = ManagedZoneOperationsClient.GetRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.operation = operation
    }
    return try await self.`get`(request: request)
  }

  public func list(request: ManagedZoneOperationsClient.ListRequest) async throws
    -> ManagedZoneOperationsListResponse
  {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: ManagedZoneOperationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> ManagedZoneOperationsListResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listByItems(
    request: ManagedZoneOperationsClient.ListRequest
  ) -> any AsyncSequence<Operation, Swift.Error> & Sendable {
    self.listByItems(request: request, options: .init())
  }

  /// Enumerates Operations for the given ManagedZone.
  ///
  /// @Snippet(path: "managedZoneOperations_list")
  public func listByItems(
    request: ManagedZoneOperationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> ManagedZoneOperationsListResponse in
      var request = request
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listByItems(
    project: Swift.String,
    managedZone: Swift.String,
  ) -> any AsyncSequence<Operation, Swift.Error> & Sendable {
    let request = ManagedZoneOperationsClient.ListRequest().with {
      $0.project = project
      $0.managedZone = managedZone
    }
    return self.listByItems(request: request)
  }
}
