// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

extension ManagedZoneOperationsClient {
  /// Synthetic request message for the [get()][.managedZoneOperations.get] method.
  public struct GetRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the operation addressed by this request (ID of the operation).
    public var operation: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Initialize a new instance of `GetRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GetRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZoneOperations.getRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [list()][.managedZoneOperations.list] method.
  public struct ListRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Identifies the managed zone addressed by this request.
    public var managedZone: Swift.String = Swift.String()

    /// Optional. Maximum number of results to be returned. If unspecified, the server decides how many results to return.
    public var maxResults: Swift.Int32? = nil

    /// Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
    public var pageToken: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Sorting criterion. The only supported values are START_TIME and ID.
    public var sortBy: ManagedZoneOperationsClient.ListRequest.SortBy? = nil

    /// Initialize a new instance of `ListRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListRequest().with { $0.managedZone = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The enumerated type for the [sortBy][.managedZoneOperations.listRequest.sortBy] field.
    public enum SortBy: Codable, Equatable, Sendable {
      case startTime
      case id
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .startTime
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .startTime: return 0
        case .id: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .startTime: return "startTime"
        case .id: return "id"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SortBy/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "startTime": self = .startTime
        case "id": self = .id
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SortBy/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .startTime
        case 1: self = .id
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .startTime: return try container.encode(0)
        case .id: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.managedZoneOperations.listRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
}
