// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// Service for the `managedZones` resource.
///
/// @Snippet(path: "managedZonesQuickstart")
public final class ManagedZonesClient: Clients.ManagedZonesProtocol, Sendable {
  let inner: any Clients.ManagedZonesStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `ManagedZonesClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ManagedZonesStub = try Clients.ManagedZonesTransport(options)
    inner = Clients.ManagedZonesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ManagedZonesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new ManagedZone. Note: While `dns.managedZones.create` is the baseline permission required to invoke this method, additional permissions are required if the managed zone configuration references other resources.
  ///
  /// @Snippet(path: "managedZones_create")
  public func create(
    request: ManagedZonesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ManagedZone {
    try await self.inner.create(request: request, options: options)
  }

  /// Deletes a previously created ManagedZone.
  ///
  /// @Snippet(path: "managedZones_delete")
  public func delete(
    request: ManagedZonesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.delete(request: request, options: options)
  }

  /// Fetches the representation of an existing ManagedZone.
  ///
  /// @Snippet(path: "managedZones_get")
  public func `get`(
    request: ManagedZonesClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ManagedZone {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "managedZones_getIamPolicy")
  public func getIamPolicy(
    request: ManagedZonesClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Enumerates ManagedZones that have been created but not yet deleted.
  ///
  /// @Snippet(path: "managedZones_list")
  public func list(
    request: ManagedZonesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ManagedZonesListResponse {
    try await self.inner.list(request: request, options: options)
  }

  /// Enumerates ManagedZones that have been created but not yet deleted.
  ///
  /// @Snippet(path: "managedZones_list")
  public func list(
    byItem: ManagedZonesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ManagedZone, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ManagedZonesListResponse in
      var request = byItem
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Applies a partial update to an existing ManagedZone.
  ///
  /// @Snippet(path: "managedZones_patch")
  public func patch(
    request: ManagedZonesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation {
    try await self.inner.patch(request: request, options: options)
  }

  /// Applies a partial update to an existing ManagedZone.
  ///
  /// @Snippet(path: "managedZones_patch")
  public func patch(
    withPolling: ManagedZonesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    let extractStatus = {
      (op: Operation) throws -> GoogleCloudGax._PollableOperationImpl<Operation>.State in
      guard op._done() else {
        return .init(done: false, result: nil)
      }

      do {
        try op._detectErrors()
      } catch let e as GoogleCloudGax.RequestError {
        return .init(done: true, result: .failure(e))
      }
      return .init(done: true, result: .success(op))
    }
    let rawOp = try await self.patch(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Operation>.State in
      let op = try await self.getOperation(
        request: .init().with {
          $0.operation = rawOp._name()
          $0.project = withPolling.project
          $0.managedZone = withPolling.managedZone
        }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll
    )
  }

  /// Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
  ///
  /// @Snippet(path: "managedZones_setIamPolicy")
  public func setIamPolicy(
    request: ManagedZonesClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the resource does not exist, this returns an empty set of permissions, not a `NOT_FOUND` error. Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "managedZones_testIamPermissions")
  public func testIamPermissions(
    request: ManagedZonesClient.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Updates an existing ManagedZone.
  ///
  /// @Snippet(path: "managedZones_update")
  public func update(
    request: ManagedZonesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation {
    try await self.inner.update(request: request, options: options)
  }

  /// Updates an existing ManagedZone.
  ///
  /// @Snippet(path: "managedZones_update")
  public func update(
    withPolling: ManagedZonesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    let extractStatus = {
      (op: Operation) throws -> GoogleCloudGax._PollableOperationImpl<Operation>.State in
      guard op._done() else {
        return .init(done: false, result: nil)
      }

      do {
        try op._detectErrors()
      } catch let e as GoogleCloudGax.RequestError {
        return .init(done: true, result: .failure(e))
      }
      return .init(done: true, result: .success(op))
    }
    let rawOp = try await self.update(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Operation>.State in
      let op = try await self.getOperation(
        request: .init().with {
          $0.operation = rawOp._name()
          $0.project = withPolling.project
          $0.managedZone = withPolling.managedZone
        }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll
    )
  }

  /// Fetches the representation of an existing Operation.
  ///
  /// @Snippet(path: "managedZones_getOperation")
  func getOperation(
    request: ManagedZoneOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ManagedZonesClient`.
  ///
  /// To mock `ManagedZonesClient` change your functions to receive
  /// `some ManagedZonesProtocol` or `any ManagedZonesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ManagedZonesProtocol {
    /// See `ManagedZonesClient.create`.
    func create(request: ManagedZonesClient.CreateRequest) async throws -> ManagedZone

    /// See `ManagedZonesClient.create`.
    func create(
      project: Swift.String,
      body: ManagedZone?,
    ) async throws -> ManagedZone

    /// See `ManagedZonesClient.delete`.
    func delete(request: ManagedZonesClient.DeleteRequest) async throws

    /// See `ManagedZonesClient.delete`.
    func delete(
      project: Swift.String,
      managedZone: Swift.String,
    ) async throws

    /// See `ManagedZonesClient.`get``.
    func `get`(request: ManagedZonesClient.GetRequest) async throws -> ManagedZone

    /// See `ManagedZonesClient.`get``.
    func `get`(
      project: Swift.String,
      managedZone: Swift.String,
    ) async throws -> ManagedZone

    /// See `ManagedZonesClient.getIamPolicy`.
    func getIamPolicy(request: ManagedZonesClient.GetIamPolicyRequest) async throws
      -> GoogleIamV1Policy

    /// See `ManagedZonesClient.getIamPolicy`.
    func getIamPolicy(
      resource: Swift.String,
      body: GoogleIamV1GetIamPolicyRequest?,
    ) async throws -> GoogleIamV1Policy

    /// See `ManagedZonesClient.list`.
    func list(request: ManagedZonesClient.ListRequest) async throws -> ManagedZonesListResponse

    /// See `ManagedZonesClient.list`.
    func list(
      byItem: ManagedZonesClient.ListRequest
    ) throws -> any AsyncSequence<ManagedZone, Swift.Error>

    /// See `ManagedZonesClient.list`.
    func list(
      project: Swift.String,
    ) throws -> any AsyncSequence<ManagedZone, Swift.Error>

    /// See `ManagedZonesClient.patch`.
    func patch(request: ManagedZonesClient.PatchRequest) async throws -> Operation

    /// See `ManagedZonesClient.setIamPolicy`.
    func setIamPolicy(request: ManagedZonesClient.SetIamPolicyRequest) async throws
      -> GoogleIamV1Policy

    /// See `ManagedZonesClient.setIamPolicy`.
    func setIamPolicy(
      resource: Swift.String,
      body: GoogleIamV1SetIamPolicyRequest?,
    ) async throws -> GoogleIamV1Policy

    /// See `ManagedZonesClient.testIamPermissions`.
    func testIamPermissions(request: ManagedZonesClient.TestIamPermissionsRequest) async throws
      -> GoogleIamV1TestIamPermissionsResponse

    /// See `ManagedZonesClient.testIamPermissions`.
    func testIamPermissions(
      resource: Swift.String,
      body: GoogleIamV1TestIamPermissionsRequest?,
    ) async throws -> GoogleIamV1TestIamPermissionsResponse

    /// See `ManagedZonesClient.update`.
    func update(request: ManagedZonesClient.UpdateRequest) async throws -> Operation

    /// See `ManagedZonesClient.create`.
    func create(
      request: ManagedZonesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ManagedZone

    /// See `ManagedZonesClient.delete`.
    func delete(
      request: ManagedZonesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ManagedZonesClient.`get``.
    func `get`(
      request: ManagedZonesClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ManagedZone

    /// See `ManagedZonesClient.getIamPolicy`.
    func getIamPolicy(
      request: ManagedZonesClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1Policy

    /// See `ManagedZonesClient.list`.
    func list(
      request: ManagedZonesClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ManagedZonesListResponse

    /// See `ManagedZonesClient.list`.
    func list(
      byItem: ManagedZonesClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ManagedZone, Swift.Error>

    /// See `ManagedZonesClient.patch`.
    func patch(
      request: ManagedZonesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Operation

    /// See `ManagedZonesClient.setIamPolicy`.
    func setIamPolicy(
      request: ManagedZonesClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1Policy

    /// See `ManagedZonesClient.testIamPermissions`.
    func testIamPermissions(
      request: ManagedZonesClient.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1TestIamPermissionsResponse

    /// See `ManagedZonesClient.update`.
    func update(
      request: ManagedZonesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Operation
  }
}

// Default implementations
extension Clients.ManagedZonesProtocol {
  public func create(request: ManagedZonesClient.CreateRequest) async throws -> ManagedZone {
    try await self.create(request: request, options: .init())
  }

  public func create(
    request: ManagedZonesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ManagedZone {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func create(
    project: Swift.String,
    body: ManagedZone?,
  ) async throws -> ManagedZone {
    let request = ManagedZonesClient.CreateRequest().with {
      $0.project = project
      $0.body = body
    }
    return try await self.create(request: request)
  }

  public func delete(request: ManagedZonesClient.DeleteRequest) async throws {
    try await self.delete(request: request, options: .init())
  }

  public func delete(
    request: ManagedZonesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func delete(
    project: Swift.String,
    managedZone: Swift.String,
  ) async throws {
    let request = ManagedZonesClient.DeleteRequest().with {
      $0.project = project
      $0.managedZone = managedZone
    }
    try await self.delete(request: request)
  }

  public func `get`(request: ManagedZonesClient.GetRequest) async throws -> ManagedZone {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: ManagedZonesClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ManagedZone {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func `get`(
    project: Swift.String,
    managedZone: Swift.String,
  ) async throws -> ManagedZone {
    let request = ManagedZonesClient.GetRequest().with {
      $0.project = project
      $0.managedZone = managedZone
    }
    return try await self.`get`(request: request)
  }

  public func getIamPolicy(request: ManagedZonesClient.GetIamPolicyRequest) async throws
    -> GoogleIamV1Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: ManagedZonesClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(
    resource: Swift.String,
    body: GoogleIamV1GetIamPolicyRequest?,
  ) async throws -> GoogleIamV1Policy {
    let request = ManagedZonesClient.GetIamPolicyRequest().with {
      $0.resource = resource
      $0.body = body
    }
    return try await self.getIamPolicy(request: request)
  }

  public func list(request: ManagedZonesClient.ListRequest) async throws -> ManagedZonesListResponse
  {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: ManagedZonesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ManagedZonesListResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func list(
    byItem: ManagedZonesClient.ListRequest
  ) throws -> any AsyncSequence<ManagedZone, Swift.Error> {
    try self.list(byItem: byItem, options: .init())
  }

  public func list(
    byItem: ManagedZonesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ManagedZone, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ManagedZonesListResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func list(
    project: Swift.String,
  ) throws -> any AsyncSequence<ManagedZone, Swift.Error> {
    let request = ManagedZonesClient.ListRequest().with {
      $0.project = project
    }
    return try self.list(byItem: request)
  }

  public func patch(request: ManagedZonesClient.PatchRequest) async throws -> Operation {
    try await self.patch(request: request, options: .init())
  }

  public func patch(
    request: ManagedZonesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func patch(
    withPolling: ManagedZonesClient.PatchRequest
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    try await self.patch(withPolling: withPolling, options: .init())
  }

  public func patch(
    withPolling: ManagedZonesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Operation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func patch(
    project: Swift.String,
    managedZone: Swift.String,
    body: ManagedZone?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    let request = ManagedZonesClient.PatchRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.body = body
    }
    return try await self.patch(withPolling: request)
  }

  public func setIamPolicy(request: ManagedZonesClient.SetIamPolicyRequest) async throws
    -> GoogleIamV1Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: ManagedZonesClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(
    resource: Swift.String,
    body: GoogleIamV1SetIamPolicyRequest?,
  ) async throws -> GoogleIamV1Policy {
    let request = ManagedZonesClient.SetIamPolicyRequest().with {
      $0.resource = resource
      $0.body = body
    }
    return try await self.setIamPolicy(request: request)
  }

  public func testIamPermissions(request: ManagedZonesClient.TestIamPermissionsRequest) async throws
    -> GoogleIamV1TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: ManagedZonesClient.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(
    resource: Swift.String,
    body: GoogleIamV1TestIamPermissionsRequest?,
  ) async throws -> GoogleIamV1TestIamPermissionsResponse {
    let request = ManagedZonesClient.TestIamPermissionsRequest().with {
      $0.resource = resource
      $0.body = body
    }
    return try await self.testIamPermissions(request: request)
  }

  public func update(request: ManagedZonesClient.UpdateRequest) async throws -> Operation {
    try await self.update(request: request, options: .init())
  }

  public func update(
    request: ManagedZonesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func update(
    withPolling: ManagedZonesClient.UpdateRequest
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    try await self.update(withPolling: withPolling, options: .init())
  }

  public func update(
    withPolling: ManagedZonesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Operation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func update(
    project: Swift.String,
    managedZone: Swift.String,
    body: ManagedZone?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Operation> {
    let request = ManagedZonesClient.UpdateRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.body = body
    }
    return try await self.update(withPolling: request)
  }

  public func getOperation(request: ManagedZoneOperationsClient.GetRequest) async throws
    -> Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: ManagedZoneOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
