// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

public struct ManagedZonePrivateVisibilityConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The list of Google Kubernetes Engine clusters that can see this zone.
  public var gkeClusters: [ManagedZonePrivateVisibilityConfigGKECluster] = []

  public var kind: Swift.String? = nil

  /// The list of VPC networks that can see this zone.
  public var networks: [ManagedZonePrivateVisibilityConfigNetwork] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ManagedZonePrivateVisibilityConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ManagedZonePrivateVisibilityConfig().with { $0.gkeClusters = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gkeClusters = CodingKeys(stringValue: "gkeClusters")
    static let kind = CodingKeys(stringValue: "kind")
    static let networks = CodingKeys(stringValue: "networks")

    static let _knownKeys: Set<Swift.String> = [
      "gkeClusters",
      "kind",
      "networks",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [ManagedZonePrivateVisibilityConfigGKECluster].self, forKey: .gkeClusters)
    {
      self.gkeClusters = value
    }
    self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
    if let value = try container.decodeIfPresent(
      [ManagedZonePrivateVisibilityConfigNetwork].self, forKey: .networks)
    {
      self.networks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gkeClusters, forKey: .gkeClusters)
    try container.encodeIfPresent(self.kind, forKey: .kind)
    try container.encode(self.networks, forKey: .networks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.ManagedZonePrivateVisibilityConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
