// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class OperationsLogging: OperationsStub {
    let inner: any OperationsStub
    let logger: Logger

    public init(_ inner: any OperationsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = ""
      logger[metadataKey: "gcp.client.service"] = "dns"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Operations"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func cancel(
      request: OperationsClient.CancelRequest, options: GoogleGax.RequestOptions
    ) async throws -> Empty {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancel",
        action: {
          (r: OperationsClient.CancelRequest, o: GoogleGax.RequestOptions) async throws -> Empty
          in
          return try await self.inner.cancel(request: r, options: o)
        })
    }

    public func delete(
      request: OperationsClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> Empty {
      try await self._intercept(
        request: request,
        options: options,
        name: "delete",
        action: {
          (r: OperationsClient.DeleteRequest, o: GoogleGax.RequestOptions) async throws -> Empty
          in
          return try await self.inner.delete(request: r, options: o)
        })
    }

    public func `get`(
      request: OperationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongrunningOperation {
      try await self._intercept(
        request: request,
        options: options,
        name: "`get`",
        action: {
          (r: OperationsClient.GetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongrunningOperation
          in
          return try await self.inner.`get`(request: r, options: o)
        })
    }

    public func list(
      request: OperationsClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongrunningListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "list",
        action: {
          (r: OperationsClient.ListRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongrunningListOperationsResponse
          in
          return try await self.inner.list(request: r, options: o)
        })
    }
  }
}
