// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for the `operations` resource.
///
/// @Snippet(path: "operationsQuickstart")
public final class OperationsClient: Clients.OperationsProtocol, Sendable {
  let inner: any Clients.OperationsStub

  /// Creates a new `OperationsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.OperationsStub = try Clients.OperationsTransport(options)
    inner = Clients.OperationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OperationsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of `1`, corresponding to `Code.CANCELLED`.
  ///
  /// @Snippet(path: "operations_cancel")
  public func cancel(
    request: OperationsClient.CancelRequest, options: GoogleGax.RequestOptions
  ) async throws -> Empty {
    try await self.inner.cancel(request: request, options: options)
  }

  /// Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "operations_delete")
  public func delete(
    request: OperationsClient.DeleteRequest, options: GoogleGax.RequestOptions
  ) async throws -> Empty {
    try await self.inner.delete(request: request, options: options)
  }

  /// Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
  ///
  /// @Snippet(path: "operations_get")
  public func `get`(
    request: OperationsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "operations_list")
  public func list(
    request: OperationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningListOperationsResponse {
    try await self.inner.list(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OperationsClient`.
  ///
  /// To mock `OperationsClient` change your functions to receive
  /// `some OperationsProtocol` or `any OperationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OperationsProtocol: Sendable {
    /// See `OperationsClient.cancel`.
    func cancel(
      request: OperationsClient.CancelRequest, options: GoogleGax.RequestOptions
    ) async throws -> Empty

    /// See `OperationsClient.delete`.
    func delete(
      request: OperationsClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> Empty

    /// See `OperationsClient.`get``.
    func `get`(
      request: OperationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongrunningOperation

    /// See `OperationsClient.list`.
    func list(
      request: OperationsClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongrunningListOperationsResponse
  }
}

// Default implementations
extension Clients.OperationsProtocol {
  public func cancel(request: OperationsClient.CancelRequest) async throws -> Empty {
    try await self.cancel(request: request, options: .init())
  }

  public func cancel(
    request: OperationsClient.CancelRequest, options: GoogleGax.RequestOptions
  ) async throws -> Empty {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancel(
    name: Swift.String,
  ) async throws -> Empty {
    let request = OperationsClient.CancelRequest().with {
      $0.name = name
    }
    return try await self.cancel(request: request)
  }

  public func delete(request: OperationsClient.DeleteRequest) async throws -> Empty {
    try await self.delete(request: request, options: .init())
  }

  public func delete(
    request: OperationsClient.DeleteRequest, options: GoogleGax.RequestOptions
  ) async throws -> Empty {
    throw GoogleGax.RequestError.unimplemented
  }

  public func delete(
    name: Swift.String,
  ) async throws -> Empty {
    let request = OperationsClient.DeleteRequest().with {
      $0.name = name
    }
    return try await self.delete(request: request)
  }

  public func `get`(request: OperationsClient.GetRequest) async throws -> GoogleLongrunningOperation
  {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: OperationsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func `get`(
    name: Swift.String,
  ) async throws -> GoogleLongrunningOperation {
    let request = OperationsClient.GetRequest().with {
      $0.name = name
    }
    return try await self.`get`(request: request)
  }

  public func list(request: OperationsClient.ListRequest) async throws
    -> GoogleLongrunningListOperationsResponse
  {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: OperationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listByItems(
    request: OperationsClient.ListRequest
  ) -> some AsyncSequence<GoogleLongrunningOperation, any Swift.Error> & Sendable {
    self.listByItems(request: request, options: .init())
  }

  /// Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "operations_list")
  public func listByItems(
    request: OperationsClient.ListRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongrunningOperation, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongrunningListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listByItems(
    name: Swift.String,
  ) -> some AsyncSequence<GoogleLongrunningOperation, any Swift.Error> & Sendable {
    let request = OperationsClient.ListRequest().with {
      $0.name = name
    }
    return self.listByItems(request: request)
  }
}
