// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for the `outboundEndpoints` resource.
///
/// @Snippet(path: "outboundEndpointsQuickstart")
public final class OutboundEndpointsClient: Clients.OutboundEndpointsProtocol, Sendable {
  let inner: any Clients.OutboundEndpointsStub

  /// Creates a new `OutboundEndpointsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.OutboundEndpointsStub = try Clients.OutboundEndpointsTransport(options)
    inner = Clients.OutboundEndpointsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OutboundEndpointsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new Outbound Endpoint.
  ///
  /// @Snippet(path: "outboundEndpoints_create")
  public func create(
    request: OutboundEndpointsClient.CreateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    try await self.inner.create(request: request, options: options)
  }

  /// Deletes a previously created Outbound Endpoint.
  ///
  /// @Snippet(path: "outboundEndpoints_delete")
  public func delete(
    request: OutboundEndpointsClient.DeleteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    try await self.inner.delete(request: request, options: options)
  }

  /// Fetches the representation of an existing Outbound Endpoint.
  ///
  /// @Snippet(path: "outboundEndpoints_get")
  public func `get`(
    request: OutboundEndpointsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> OutboundEndpoint {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Enumerates all Outbound Endpoints associated with a project.
  ///
  /// @Snippet(path: "outboundEndpoints_list")
  public func list(
    request: OutboundEndpointsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> ListOutboundEndpointsResponse {
    try await self.inner.list(request: request, options: options)
  }

  /// Updates an existing Outbound Endpoint.
  ///
  /// @Snippet(path: "outboundEndpoints_patch")
  public func patch(
    request: OutboundEndpointsClient.PatchRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    try await self.inner.patch(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OutboundEndpointsClient`.
  ///
  /// To mock `OutboundEndpointsClient` change your functions to receive
  /// `some OutboundEndpointsProtocol` or `any OutboundEndpointsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OutboundEndpointsProtocol: Sendable {
    /// See `OutboundEndpointsClient.create`.
    func create(
      request: OutboundEndpointsClient.CreateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongrunningOperation

    /// See `OutboundEndpointsClient.delete`.
    func delete(
      request: OutboundEndpointsClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongrunningOperation

    /// See `OutboundEndpointsClient.`get``.
    func `get`(
      request: OutboundEndpointsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> OutboundEndpoint

    /// See `OutboundEndpointsClient.list`.
    func list(
      request: OutboundEndpointsClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> ListOutboundEndpointsResponse

    /// See `OutboundEndpointsClient.patch`.
    func patch(
      request: OutboundEndpointsClient.PatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongrunningOperation
  }
}

// Default implementations
extension Clients.OutboundEndpointsProtocol {
  public func create(request: OutboundEndpointsClient.CreateRequest) async throws
    -> GoogleLongrunningOperation
  {
    try await self.create(request: request, options: .init())
  }

  public func create(
    request: OutboundEndpointsClient.CreateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func create(
    parent: Swift.String,
    body: OutboundEndpoint?,
  ) async throws -> GoogleLongrunningOperation {
    let request = OutboundEndpointsClient.CreateRequest().with {
      $0.parent = parent
      $0.body = body
    }
    return try await self.create(request: request)
  }

  public func delete(request: OutboundEndpointsClient.DeleteRequest) async throws
    -> GoogleLongrunningOperation
  {
    try await self.delete(request: request, options: .init())
  }

  public func delete(
    request: OutboundEndpointsClient.DeleteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func delete(
    name: Swift.String,
  ) async throws -> GoogleLongrunningOperation {
    let request = OutboundEndpointsClient.DeleteRequest().with {
      $0.name = name
    }
    return try await self.delete(request: request)
  }

  public func `get`(request: OutboundEndpointsClient.GetRequest) async throws -> OutboundEndpoint {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: OutboundEndpointsClient.GetRequest, options: GoogleGax.RequestOptions
  ) async throws -> OutboundEndpoint {
    throw GoogleGax.RequestError.unimplemented
  }

  public func `get`(
    name: Swift.String,
  ) async throws -> OutboundEndpoint {
    let request = OutboundEndpointsClient.GetRequest().with {
      $0.name = name
    }
    return try await self.`get`(request: request)
  }

  public func list(request: OutboundEndpointsClient.ListRequest) async throws
    -> ListOutboundEndpointsResponse
  {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: OutboundEndpointsClient.ListRequest, options: GoogleGax.RequestOptions
  ) async throws -> ListOutboundEndpointsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listByItems(
    request: OutboundEndpointsClient.ListRequest
  ) -> some AsyncSequence<OutboundEndpoint, any Swift.Error> & Sendable {
    self.listByItems(request: request, options: .init())
  }

  /// Enumerates all Outbound Endpoints associated with a project.
  ///
  /// @Snippet(path: "outboundEndpoints_list")
  public func listByItems(
    request: OutboundEndpointsClient.ListRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<OutboundEndpoint, any Swift.Error> & Sendable {
    let listRpc = { @Sendable (token: Swift.String) async throws -> ListOutboundEndpointsResponse in
      var request = request
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<OutboundEndpoint, any Swift.Error> & Sendable {
    let request = OutboundEndpointsClient.ListRequest().with {
      $0.parent = parent
    }
    return self.listByItems(request: request)
  }

  public func patch(request: OutboundEndpointsClient.PatchRequest) async throws
    -> GoogleLongrunningOperation
  {
    try await self.patch(request: request, options: .init())
  }

  public func patch(
    request: OutboundEndpointsClient.PatchRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongrunningOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func patch(
    name: Swift.String,
    body: OutboundEndpoint?,
  ) async throws -> GoogleLongrunningOperation {
    let request = OutboundEndpointsClient.PatchRequest().with {
      $0.name = name
      $0.body = body
    }
    return try await self.patch(request: request)
  }
}
