// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An OutboundEndpoint is a regional resource to enable outbound forwarding from a private IP range in VPCs to on-premise or other networks.
public struct OutboundEndpoint: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Annotations as key value pairs
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. User provided description.
  public var description: Swift.String? = nil

  /// Required. Immutable. User provided IP address to use for outbound DNS forwarding. This address must be a free address on the subnetwork.
  public var endpointIp: Swift.String? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Identifier. The resource name of the OutboundEndpoint. Format: `projects/{project}/locations/{location}/outboundEndpoints/{outboundEndpoint}`
  public var name: Swift.String? = nil

  /// Required. Immutable. The VPC network containing the outbound endpoint, specified as full path.
  public var network: Swift.String? = nil

  /// Required. Immutable. The subnetwork holding the endpoint_ip, specified as full path.
  public var subnetwork: Swift.String? = nil

  /// Optional. Tag bindings as key value pairs
  public var tags: [Swift.String: Swift.String] = [:]

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OutboundEndpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OutboundEndpoint().with { $0.annotations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let annotations = CodingKeys(stringValue: "annotations")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let description = CodingKeys(stringValue: "description")
    static let endpointIp = CodingKeys(stringValue: "endpointIp")
    static let labels = CodingKeys(stringValue: "labels")
    static let name = CodingKeys(stringValue: "name")
    static let network = CodingKeys(stringValue: "network")
    static let subnetwork = CodingKeys(stringValue: "subnetwork")
    static let tags = CodingKeys(stringValue: "tags")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "annotations",
      "createTime",
      "description",
      "endpointIp",
      "labels",
      "name",
      "network",
      "subnetwork",
      "tags",
      "updateTime",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    self.endpointIp = try container.decodeIfPresent(Swift.String.self, forKey: .endpointIp)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
    self.network = try container.decodeIfPresent(Swift.String.self, forKey: .network)
    self.subnetwork = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encodeIfPresent(self.endpointIp, forKey: .endpointIp)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.name, forKey: .name)
    try container.encodeIfPresent(self.network, forKey: .network)
    try container.encodeIfPresent(self.subnetwork, forKey: .subnetwork)
    try container.encode(self.tags, forKey: .tags)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `OutboundEndpoint`: `"type.googleapis.com/.OutboundEndpoint"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.OutboundEndpoint"
  }

  /// Initialize an instance of `OutboundEndpoint` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/.OutboundEndpoint"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `OutboundEndpoint` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
