// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A policy is a collection of DNS rules applied to one or more Virtual Private Cloud resources.
public struct Policy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Sets an alternative name server for the associated networks. When specified, all DNS queries are forwarded to a name server that you choose. Names such as .internal are not available when an alternative name server is specified.
  public var alternativeNameServerConfig: PolicyAlternativeNameServerConfig? = nil

  /// A mutable string of at most 1024 characters associated with this resource for the user's convenience. Has no effect on the policy's function.
  public var description: Swift.String? = nil

  /// Configurations related to DNS64 for this policy.
  public var dns64Config: PolicyDns64Config? = nil

  /// Allows networks bound to this policy to receive DNS queries sent by VMs or applications over VPN connections. When enabled, a virtual IP address is allocated from each of the subnetworks that are bound to this policy.
  public var enableInboundForwarding: Swift.Bool? = nil

  /// Controls whether logging is enabled for the networks bound to this policy. Defaults to no logging if not set.
  public var enableLogging: Swift.Bool? = nil

  /// Unique identifier for the resource; defined by the server (output only).
  public var id: Swift.UInt64? = nil

  public var kind: Swift.String? = nil

  /// User-assigned name for this policy.
  public var name: Swift.String? = nil

  /// List of network names specifying networks to which this policy is applied.
  public var networks: [PolicyNetwork] = []

  /// Initialize a new instance of `Policy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Policy().with { $0.alternativeNameServerConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.Policy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
