// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

extension PoliciesClient {
  /// Synthetic request message for the [create()][.policies.create] method.
  public struct CreateRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [create()][.policies.create] method.
    public var body: Policy? = nil

    /// Initialize a new instance of `CreateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.policies.createRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [delete()][.policies.delete] method.
  public struct DeleteRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// User given friendly name of the policy addressed by this request.
    public var policy: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Initialize a new instance of `DeleteRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeleteRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.policies.deleteRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [get()][.policies.get] method.
  public struct GetRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// User given friendly name of the policy addressed by this request.
    public var policy: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Initialize a new instance of `GetRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GetRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.policies.getRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [list()][.policies.list] method.
  public struct ListRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Maximum number of results to be returned. If unspecified, the server decides how many results to return.
    public var maxResults: Swift.Int32? = nil

    /// Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
    public var pageToken: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Initialize a new instance of `ListRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListRequest().with { $0.maxResults = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.policies.listRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [patch()][.policies.patch] method.
  public struct PatchRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// User given friendly name of the policy addressed by this request.
    public var policy: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [patch()][.policies.patch] method.
    public var body: Policy? = nil

    /// Initialize a new instance of `PatchRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PatchRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.policies.patchRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [update()][.policies.update] method.
  public struct UpdateRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// User given friendly name of the policy addressed by this request.
    public var policy: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [update()][.policies.update] method.
    public var body: Policy? = nil

    /// Initialize a new instance of `UpdateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpdateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.policies.updateRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
}
