// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Limits associated with a Project.
public struct Quota: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Maximum allowed number of DnsKeys per ManagedZone.
  public var dnsKeysPerManagedZone: Swift.Int32? = nil

  /// Maximum allowed number of GKE clusters to which a privately scoped zone can be attached.
  public var gkeClustersPerManagedZone: Swift.Int32? = nil

  /// Maximum allowed number of GKE clusters per policy.
  public var gkeClustersPerPolicy: Swift.Int32? = nil

  /// Maximum allowed number of GKE clusters per response policy.
  public var gkeClustersPerResponsePolicy: Swift.Int32? = nil

  public var internetHealthChecksPerManagedZone: Swift.Int32? = nil

  /// Maximum allowed number of items per routing policy.
  public var itemsPerRoutingPolicy: Swift.Int32? = nil

  public var kind: Swift.String? = nil

  /// Maximum allowed number of managed zones in the project.
  public var managedZones: Swift.Int32? = nil

  /// Maximum allowed number of managed zones which can be attached to a GKE cluster.
  public var managedZonesPerGkeCluster: Swift.Int32? = nil

  /// Maximum allowed number of managed zones which can be attached to a network.
  public var managedZonesPerNetwork: Swift.Int32? = nil

  /// Maximum number of nameservers per delegation, meant to prevent abuse
  public var nameserversPerDelegation: Swift.Int32? = nil

  /// Maximum allowed number of networks to which a privately scoped zone can be attached.
  public var networksPerManagedZone: Swift.Int32? = nil

  /// Maximum allowed number of networks per policy.
  public var networksPerPolicy: Swift.Int32? = nil

  /// Maximum allowed number of networks per response policy.
  public var networksPerResponsePolicy: Swift.Int32? = nil

  /// Maximum allowed number of consumer peering zones per target network owned by this producer project
  public var peeringZonesPerTargetNetwork: Swift.Int32? = nil

  /// Maximum allowed number of policies per project.
  public var policies: Swift.Int32? = nil

  /// Maximum allowed number of ResourceRecords per ResourceRecordSet.
  public var resourceRecordsPerRrset: Swift.Int32? = nil

  /// Maximum allowed number of response policies per project.
  public var responsePolicies: Swift.Int32? = nil

  /// Maximum allowed number of rules per response policy.
  public var responsePolicyRulesPerResponsePolicy: Swift.Int32? = nil

  /// Maximum allowed number of ResourceRecordSets to add per ChangesCreateRequest.
  public var rrsetAdditionsPerChange: Swift.Int32? = nil

  /// Maximum allowed number of ResourceRecordSets to delete per ChangesCreateRequest.
  public var rrsetDeletionsPerChange: Swift.Int32? = nil

  /// Maximum allowed number of ResourceRecordSets per zone in the project.
  public var rrsetsPerManagedZone: Swift.Int32? = nil

  /// Maximum allowed number of target name servers per managed forwarding zone.
  public var targetNameServersPerManagedZone: Swift.Int32? = nil

  /// Maximum allowed number of alternative target name servers per policy.
  public var targetNameServersPerPolicy: Swift.Int32? = nil

  /// Maximum allowed size for total rrdata in one ChangesCreateRequest in bytes.
  public var totalRrdataSizePerChange: Swift.Int32? = nil

  /// DNSSEC algorithm and key length types that can be used for DnsKeys.
  public var whitelistedKeySpecs: [DnsKeySpec] = []

  /// Initialize a new instance of `Quota`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Quota().with { $0.dnsKeysPerManagedZone = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.Quota"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
