// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// Service for the `resourceRecordSets` resource.
///
/// @Snippet(path: "resourceRecordSetsQuickstart")
public final class ResourceRecordSetsClient: Clients.ResourceRecordSetsProtocol, Sendable {
  let inner: any Clients.ResourceRecordSetsStub

  /// Creates a new `ResourceRecordSetsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ResourceRecordSetsStub = try Clients.ResourceRecordSetsTransport(options)
    inner = Clients.ResourceRecordSetsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ResourceRecordSetsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new ResourceRecordSet.
  ///
  /// @Snippet(path: "resourceRecordSets_create")
  public func create(
    request: ResourceRecordSetsClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSet {
    try await self.inner.create(request: request, options: options)
  }

  /// Deletes a previously created ResourceRecordSet.
  ///
  /// @Snippet(path: "resourceRecordSets_delete")
  public func delete(
    request: ResourceRecordSetsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSetsDeleteResponse {
    try await self.inner.delete(request: request, options: options)
  }

  /// Fetches the representation of an existing ResourceRecordSet.
  ///
  /// @Snippet(path: "resourceRecordSets_get")
  public func `get`(
    request: ResourceRecordSetsClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSet {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Enumerates ResourceRecordSets that you have created but not yet deleted.
  ///
  /// @Snippet(path: "resourceRecordSets_list")
  public func list(
    request: ResourceRecordSetsClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSetsListResponse {
    try await self.inner.list(request: request, options: options)
  }

  /// Enumerates ResourceRecordSets that you have created but not yet deleted.
  ///
  /// @Snippet(path: "resourceRecordSets_list")
  public func list(
    byItem: ResourceRecordSetsClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceRecordSet, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ResourceRecordSetsListResponse in
      var request = byItem
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Applies a partial update to an existing ResourceRecordSet.
  ///
  /// @Snippet(path: "resourceRecordSets_patch")
  public func patch(
    request: ResourceRecordSetsClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSet {
    try await self.inner.patch(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ResourceRecordSetsClient`.
  ///
  /// To mock `ResourceRecordSetsClient` change your functions to receive
  /// `some ResourceRecordSetsProtocol` or `any ResourceRecordSetsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ResourceRecordSetsProtocol {
    /// See `ResourceRecordSetsClient.create`.
    func create(request: ResourceRecordSetsClient.CreateRequest) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.create`.
    func create(
      project: Swift.String,
      managedZone: Swift.String,
      body: ResourceRecordSet?,
    ) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.delete`.
    func delete(request: ResourceRecordSetsClient.DeleteRequest) async throws
      -> ResourceRecordSetsDeleteResponse

    /// See `ResourceRecordSetsClient.delete`.
    func delete(
      project: Swift.String,
      managedZone: Swift.String,
      name: Swift.String,
      type: Swift.String,
    ) async throws -> ResourceRecordSetsDeleteResponse

    /// See `ResourceRecordSetsClient.`get``.
    func `get`(request: ResourceRecordSetsClient.GetRequest) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.`get``.
    func `get`(
      project: Swift.String,
      managedZone: Swift.String,
      name: Swift.String,
      type: Swift.String,
    ) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.list`.
    func list(request: ResourceRecordSetsClient.ListRequest) async throws
      -> ResourceRecordSetsListResponse

    /// See `ResourceRecordSetsClient.list`.
    func list(
      byItem: ResourceRecordSetsClient.ListRequest
    ) throws -> any AsyncSequence<ResourceRecordSet, Swift.Error>

    /// See `ResourceRecordSetsClient.list`.
    func list(
      project: Swift.String,
      managedZone: Swift.String,
    ) throws -> any AsyncSequence<ResourceRecordSet, Swift.Error>

    /// See `ResourceRecordSetsClient.patch`.
    func patch(request: ResourceRecordSetsClient.PatchRequest) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.patch`.
    func patch(
      project: Swift.String,
      managedZone: Swift.String,
      name: Swift.String,
      type: Swift.String,
      body: ResourceRecordSet?,
    ) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.create`.
    func create(
      request: ResourceRecordSetsClient.CreateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.delete`.
    func delete(
      request: ResourceRecordSetsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSetsDeleteResponse

    /// See `ResourceRecordSetsClient.`get``.
    func `get`(
      request: ResourceRecordSetsClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSet

    /// See `ResourceRecordSetsClient.list`.
    func list(
      request: ResourceRecordSetsClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSetsListResponse

    /// See `ResourceRecordSetsClient.list`.
    func list(
      byItem: ResourceRecordSetsClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ResourceRecordSet, Swift.Error>

    /// See `ResourceRecordSetsClient.patch`.
    func patch(
      request: ResourceRecordSetsClient.PatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSet
  }
}

// Default implementations
extension Clients.ResourceRecordSetsProtocol {
  public func create(request: ResourceRecordSetsClient.CreateRequest) async throws
    -> ResourceRecordSet
  {
    try await self.create(request: request, options: .init())
  }

  public func create(
    request: ResourceRecordSetsClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func create(
    project: Swift.String,
    managedZone: Swift.String,
    body: ResourceRecordSet?,
  ) async throws -> ResourceRecordSet {
    let request = ResourceRecordSetsClient.CreateRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.body = body
    }
    return try await self.create(request: request)
  }

  public func delete(request: ResourceRecordSetsClient.DeleteRequest) async throws
    -> ResourceRecordSetsDeleteResponse
  {
    try await self.delete(request: request, options: .init())
  }

  public func delete(
    request: ResourceRecordSetsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSetsDeleteResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func delete(
    project: Swift.String,
    managedZone: Swift.String,
    name: Swift.String,
    type: Swift.String,
  ) async throws -> ResourceRecordSetsDeleteResponse {
    let request = ResourceRecordSetsClient.DeleteRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.name = name
      $0.type = type
    }
    return try await self.delete(request: request)
  }

  public func `get`(request: ResourceRecordSetsClient.GetRequest) async throws -> ResourceRecordSet
  {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: ResourceRecordSetsClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func `get`(
    project: Swift.String,
    managedZone: Swift.String,
    name: Swift.String,
    type: Swift.String,
  ) async throws -> ResourceRecordSet {
    let request = ResourceRecordSetsClient.GetRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.name = name
      $0.type = type
    }
    return try await self.`get`(request: request)
  }

  public func list(request: ResourceRecordSetsClient.ListRequest) async throws
    -> ResourceRecordSetsListResponse
  {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: ResourceRecordSetsClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSetsListResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func list(
    byItem: ResourceRecordSetsClient.ListRequest
  ) throws -> any AsyncSequence<ResourceRecordSet, Swift.Error> {
    try self.list(byItem: byItem, options: .init())
  }

  public func list(
    byItem: ResourceRecordSetsClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceRecordSet, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ResourceRecordSetsListResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func list(
    project: Swift.String,
    managedZone: Swift.String,
  ) throws -> any AsyncSequence<ResourceRecordSet, Swift.Error> {
    let request = ResourceRecordSetsClient.ListRequest().with {
      $0.project = project
      $0.managedZone = managedZone
    }
    return try self.list(byItem: request)
  }

  public func patch(request: ResourceRecordSetsClient.PatchRequest) async throws
    -> ResourceRecordSet
  {
    try await self.patch(request: request, options: .init())
  }

  public func patch(
    request: ResourceRecordSetsClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResourceRecordSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func patch(
    project: Swift.String,
    managedZone: Swift.String,
    name: Swift.String,
    type: Swift.String,
    body: ResourceRecordSet?,
  ) async throws -> ResourceRecordSet {
    let request = ResourceRecordSetsClient.PatchRequest().with {
      $0.project = project
      $0.managedZone = managedZone
      $0.name = name
      $0.type = type
      $0.body = body
    }
    return try await self.patch(request: request)
  }
}
