// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ResourceRecordSetsLogging: ResourceRecordSetsStub {
    let inner: any ResourceRecordSetsStub
    let logger: Logger

    public init(_ inner: any ResourceRecordSetsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = ""
      logger[metadataKey: "gcp.client.service"] = "dns"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ResourceRecordSets"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func create(
      request: ResourceRecordSetsClient.CreateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSet {
      try await self._intercept(
        request: request,
        options: options,
        name: "create",
        action: {
          (r: ResourceRecordSetsClient.CreateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ResourceRecordSet
          in
          return try await self.inner.create(request: r, options: o)
        })
    }

    public func delete(
      request: ResourceRecordSetsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSetsDeleteResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "delete",
        action: {
          (r: ResourceRecordSetsClient.DeleteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ResourceRecordSetsDeleteResponse
          in
          return try await self.inner.delete(request: r, options: o)
        })
    }

    public func `get`(
      request: ResourceRecordSetsClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSet {
      try await self._intercept(
        request: request,
        options: options,
        name: "`get`",
        action: {
          (r: ResourceRecordSetsClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ResourceRecordSet
          in
          return try await self.inner.`get`(request: r, options: o)
        })
    }

    public func list(
      request: ResourceRecordSetsClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSetsListResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "list",
        action: {
          (r: ResourceRecordSetsClient.ListRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ResourceRecordSetsListResponse
          in
          return try await self.inner.list(request: r, options: o)
        })
    }

    public func patch(
      request: ResourceRecordSetsClient.PatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResourceRecordSet {
      try await self._intercept(
        request: request,
        options: options,
        name: "patch",
        action: {
          (r: ResourceRecordSetsClient.PatchRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ResourceRecordSet
          in
          return try await self.inner.patch(request: r, options: o)
        })
    }
  }
}
