// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A unit of data that is returned by the DNS servers.
public struct ResourceRecordSet: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var kind: Swift.String? = nil

  /// For example, www.example.com.
  public var name: Swift.String? = nil

  /// Configures dynamic query responses based on either the geo location of the querying user or a weighted round robin based routing policy. A valid `ResourceRecordSet` contains only `rrdata` (for static resolution) or a `routing_policy` (for dynamic resolution).
  public var routingPolicy: RRSetRoutingPolicy? = nil

  /// As defined in RFC 1035 (section 5) and RFC 1034 (section 3.6.1) -- see examples.
  public var rrdatas: [Swift.String] = []

  /// As defined in RFC 4034 (section 3.2).
  public var signatureRrdatas: [Swift.String] = []

  /// Number of seconds that this `ResourceRecordSet` can be cached by resolvers.
  public var ttl: Swift.Int32? = nil

  /// The identifier of a supported record type. See the list of Supported DNS record types.
  public var type: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceRecordSet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceRecordSet().with { $0.kind = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let kind = CodingKeys(stringValue: "kind")
    static let name = CodingKeys(stringValue: "name")
    static let routingPolicy = CodingKeys(stringValue: "routingPolicy")
    static let rrdatas = CodingKeys(stringValue: "rrdatas")
    static let signatureRrdatas = CodingKeys(stringValue: "signatureRrdatas")
    static let ttl = CodingKeys(stringValue: "ttl")
    static let type = CodingKeys(stringValue: "type")

    static let _knownKeys: Set<Swift.String> = [
      "kind",
      "name",
      "routingPolicy",
      "rrdatas",
      "signatureRrdatas",
      "ttl",
      "type",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
    self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
    self.routingPolicy = try container.decodeIfPresent(
      RRSetRoutingPolicy.self, forKey: .routingPolicy)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .rrdatas) {
      self.rrdatas = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .signatureRrdatas) {
      self.signatureRrdatas = value
    }
    self.ttl = try container.decodeIfPresent(Swift.Int32.self, forKey: .ttl)
    self.type = try container.decodeIfPresent(Swift.String.self, forKey: .type)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.kind, forKey: .kind)
    try container.encodeIfPresent(self.name, forKey: .name)
    try container.encodeIfPresent(self.routingPolicy, forKey: .routingPolicy)
    try container.encode(self.rrdatas, forKey: .rrdatas)
    try container.encode(self.signatureRrdatas, forKey: .signatureRrdatas)
    try container.encodeIfPresent(self.ttl, forKey: .ttl)
    try container.encodeIfPresent(self.type, forKey: .type)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.ResourceRecordSet"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
