// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

extension ResourceRecordSetsClient {
  /// Synthetic request message for the [create()][.resourceRecordSets.create] method.
  public struct CreateRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Synthetic request body field for the [create()][.resourceRecordSets.create] method.
    public var body: ResourceRecordSet? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CreateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let project = CodingKeys(stringValue: "project")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "project",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      self.body = try container.decodeIfPresent(ResourceRecordSet.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.project, forKey: .project)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.resourceRecordSets.createRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [delete()][.resourceRecordSets.delete] method.
  public struct DeleteRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Fully qualified domain name.
    public var name: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// RRSet type.
    public var type: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DeleteRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeleteRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let name = CodingKeys(stringValue: "name")
      static let project = CodingKeys(stringValue: "project")
      static let type = CodingKeys(stringValue: "type")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "name",
        "project",
        "type",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.type, forKey: .type)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.resourceRecordSets.deleteRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [get()][.resourceRecordSets.get] method.
  public struct GetRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Fully qualified domain name.
    public var name: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// RRSet type.
    public var type: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GetRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GetRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let name = CodingKeys(stringValue: "name")
      static let project = CodingKeys(stringValue: "project")
      static let type = CodingKeys(stringValue: "type")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "name",
        "project",
        "type",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.type, forKey: .type)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.resourceRecordSets.getRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [list()][.resourceRecordSets.list] method.
  public struct ListRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Specify a filter expression to view records that exactly match the specified domain. Both the `name` and `type` parameters are not supported and must be omitted when you use `filter`. Your `filter` expression must conform to AIP-160 and you must specify a domain in the `name` field. Optionally, you can include the `type` field to filter records by type. You can also include the `has_suffix` function to view records that match by domain suffix. Examples: * `name`="example.com." * `name`="example.com." AND type="A" * `name`=`has_suffix`("example.com.") * `name`=`has_suffix`("example.com.") AND type="A"
    public var filter: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Optional. Maximum number of results to be returned. If unspecified, the server decides how many results to return.
    public var maxResults: Swift.Int32? = nil

    /// Specify a fully qualified domain name to view only those records. The `name` parameter is not supported and must be omitted when you use `filter`.
    public var name: Swift.String? = nil

    /// Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
    public var pageToken: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// Specify a record type to view only those records. You must also specify the `name` parameter. The `type` parameter is not supported and must be omitted when you use `filter`.
    public var type: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListRequest().with { $0.filter = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let filter = CodingKeys(stringValue: "filter")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let maxResults = CodingKeys(stringValue: "maxResults")
      static let name = CodingKeys(stringValue: "name")
      static let pageToken = CodingKeys(stringValue: "pageToken")
      static let project = CodingKeys(stringValue: "project")
      static let type = CodingKeys(stringValue: "type")

      static let _knownKeys: Set<Swift.String> = [
        "filter",
        "managedZone",
        "maxResults",
        "name",
        "pageToken",
        "project",
        "type",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.filter = try container.decodeIfPresent(Swift.String.self, forKey: .filter)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      self.maxResults = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxResults)
      self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
      self.pageToken = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      self.type = try container.decodeIfPresent(Swift.String.self, forKey: .type)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.filter, forKey: .filter)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encodeIfPresent(self.maxResults, forKey: .maxResults)
      try container.encodeIfPresent(self.name, forKey: .name)
      try container.encodeIfPresent(self.pageToken, forKey: .pageToken)
      try container.encode(self.project, forKey: .project)
      try container.encodeIfPresent(self.type, forKey: .type)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.resourceRecordSets.listRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [patch()][.resourceRecordSets.patch] method.
  public struct PatchRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the managed zone addressed by this request. Can be the managed zone name or ID.
    public var managedZone: Swift.String = Swift.String()

    /// Fully qualified domain name.
    public var name: Swift.String = Swift.String()

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// RRSet type.
    public var type: Swift.String = Swift.String()

    /// Synthetic request body field for the [patch()][.resourceRecordSets.patch] method.
    public var body: ResourceRecordSet? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PatchRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PatchRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let managedZone = CodingKeys(stringValue: "managedZone")
      static let name = CodingKeys(stringValue: "name")
      static let project = CodingKeys(stringValue: "project")
      static let type = CodingKeys(stringValue: "type")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "managedZone",
        "name",
        "project",
        "type",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managedZone) {
        self.managedZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      self.body = try container.decodeIfPresent(ResourceRecordSet.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.managedZone, forKey: .managedZone)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.type, forKey: .type)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.resourceRecordSets.patchRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
}
