// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// Service for the `responsePolicies` resource.
///
/// @Snippet(path: "responsePoliciesQuickstart")
public final class ResponsePoliciesClient: Clients.ResponsePoliciesProtocol, Sendable {
  let inner: any Clients.ResponsePoliciesStub

  /// Creates a new `ResponsePoliciesClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ResponsePoliciesStub = try Clients.ResponsePoliciesTransport(options)
    inner = Clients.ResponsePoliciesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ResponsePoliciesLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new Response Policy
  ///
  /// @Snippet(path: "responsePolicies_create")
  public func create(
    request: ResponsePoliciesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePolicy {
    try await self.inner.create(request: request, options: options)
  }

  /// Deletes a previously created Response Policy. Fails if the response policy is non-empty or still being referenced by a network.
  ///
  /// @Snippet(path: "responsePolicies_delete")
  public func delete(
    request: ResponsePoliciesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.delete(request: request, options: options)
  }

  /// Fetches the representation of an existing Response Policy.
  ///
  /// @Snippet(path: "responsePolicies_get")
  public func `get`(
    request: ResponsePoliciesClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePolicy {
    try await self.inner.`get`(request: request, options: options)
  }

  /// Enumerates all Response Policies associated with a project.
  ///
  /// @Snippet(path: "responsePolicies_list")
  public func list(
    request: ResponsePoliciesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePoliciesListResponse {
    try await self.inner.list(request: request, options: options)
  }

  /// Enumerates all Response Policies associated with a project.
  ///
  /// @Snippet(path: "responsePolicies_list")
  public func list(
    byItem: ResponsePoliciesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResponsePolicy, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ResponsePoliciesListResponse in
      var request = byItem
      request.pageToken = token
      return try await self.list(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Applies a partial update to an existing Response Policy.
  ///
  /// @Snippet(path: "responsePolicies_patch")
  public func patch(
    request: ResponsePoliciesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePoliciesPatchResponse {
    try await self.inner.patch(request: request, options: options)
  }

  /// Updates an existing Response Policy.
  ///
  /// @Snippet(path: "responsePolicies_update")
  public func update(
    request: ResponsePoliciesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePoliciesUpdateResponse {
    try await self.inner.update(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ResponsePoliciesClient`.
  ///
  /// To mock `ResponsePoliciesClient` change your functions to receive
  /// `some ResponsePoliciesProtocol` or `any ResponsePoliciesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ResponsePoliciesProtocol {
    /// See `ResponsePoliciesClient.create`.
    func create(request: ResponsePoliciesClient.CreateRequest) async throws -> ResponsePolicy

    /// See `ResponsePoliciesClient.create`.
    func create(
      project: Swift.String,
      body: ResponsePolicy?,
    ) async throws -> ResponsePolicy

    /// See `ResponsePoliciesClient.delete`.
    func delete(request: ResponsePoliciesClient.DeleteRequest) async throws

    /// See `ResponsePoliciesClient.delete`.
    func delete(
      project: Swift.String,
      responsePolicy: Swift.String,
    ) async throws

    /// See `ResponsePoliciesClient.`get``.
    func `get`(request: ResponsePoliciesClient.GetRequest) async throws -> ResponsePolicy

    /// See `ResponsePoliciesClient.`get``.
    func `get`(
      project: Swift.String,
      responsePolicy: Swift.String,
    ) async throws -> ResponsePolicy

    /// See `ResponsePoliciesClient.list`.
    func list(request: ResponsePoliciesClient.ListRequest) async throws
      -> ResponsePoliciesListResponse

    /// See `ResponsePoliciesClient.list`.
    func list(
      byItem: ResponsePoliciesClient.ListRequest
    ) throws -> any AsyncSequence<ResponsePolicy, Swift.Error>

    /// See `ResponsePoliciesClient.list`.
    func list(
      project: Swift.String,
    ) throws -> any AsyncSequence<ResponsePolicy, Swift.Error>

    /// See `ResponsePoliciesClient.patch`.
    func patch(request: ResponsePoliciesClient.PatchRequest) async throws
      -> ResponsePoliciesPatchResponse

    /// See `ResponsePoliciesClient.patch`.
    func patch(
      project: Swift.String,
      responsePolicy: Swift.String,
      body: ResponsePolicy?,
    ) async throws -> ResponsePoliciesPatchResponse

    /// See `ResponsePoliciesClient.update`.
    func update(request: ResponsePoliciesClient.UpdateRequest) async throws
      -> ResponsePoliciesUpdateResponse

    /// See `ResponsePoliciesClient.update`.
    func update(
      project: Swift.String,
      responsePolicy: Swift.String,
      body: ResponsePolicy?,
    ) async throws -> ResponsePoliciesUpdateResponse

    /// See `ResponsePoliciesClient.create`.
    func create(
      request: ResponsePoliciesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResponsePolicy

    /// See `ResponsePoliciesClient.delete`.
    func delete(
      request: ResponsePoliciesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ResponsePoliciesClient.`get``.
    func `get`(
      request: ResponsePoliciesClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResponsePolicy

    /// See `ResponsePoliciesClient.list`.
    func list(
      request: ResponsePoliciesClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResponsePoliciesListResponse

    /// See `ResponsePoliciesClient.list`.
    func list(
      byItem: ResponsePoliciesClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ResponsePolicy, Swift.Error>

    /// See `ResponsePoliciesClient.patch`.
    func patch(
      request: ResponsePoliciesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResponsePoliciesPatchResponse

    /// See `ResponsePoliciesClient.update`.
    func update(
      request: ResponsePoliciesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ResponsePoliciesUpdateResponse
  }
}

// Default implementations
extension Clients.ResponsePoliciesProtocol {
  public func create(request: ResponsePoliciesClient.CreateRequest) async throws -> ResponsePolicy {
    try await self.create(request: request, options: .init())
  }

  public func create(
    request: ResponsePoliciesClient.CreateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePolicy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func create(
    project: Swift.String,
    body: ResponsePolicy?,
  ) async throws -> ResponsePolicy {
    let request = ResponsePoliciesClient.CreateRequest().with {
      $0.project = project
      $0.body = body
    }
    return try await self.create(request: request)
  }

  public func delete(request: ResponsePoliciesClient.DeleteRequest) async throws {
    try await self.delete(request: request, options: .init())
  }

  public func delete(
    request: ResponsePoliciesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func delete(
    project: Swift.String,
    responsePolicy: Swift.String,
  ) async throws {
    let request = ResponsePoliciesClient.DeleteRequest().with {
      $0.project = project
      $0.responsePolicy = responsePolicy
    }
    try await self.delete(request: request)
  }

  public func `get`(request: ResponsePoliciesClient.GetRequest) async throws -> ResponsePolicy {
    try await self.`get`(request: request, options: .init())
  }

  public func `get`(
    request: ResponsePoliciesClient.GetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePolicy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func `get`(
    project: Swift.String,
    responsePolicy: Swift.String,
  ) async throws -> ResponsePolicy {
    let request = ResponsePoliciesClient.GetRequest().with {
      $0.project = project
      $0.responsePolicy = responsePolicy
    }
    return try await self.`get`(request: request)
  }

  public func list(request: ResponsePoliciesClient.ListRequest) async throws
    -> ResponsePoliciesListResponse
  {
    try await self.list(request: request, options: .init())
  }

  public func list(
    request: ResponsePoliciesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePoliciesListResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func list(
    byItem: ResponsePoliciesClient.ListRequest
  ) throws -> any AsyncSequence<ResponsePolicy, Swift.Error> {
    try self.list(byItem: byItem, options: .init())
  }

  public func list(
    byItem: ResponsePoliciesClient.ListRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResponsePolicy, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> ResponsePoliciesListResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func list(
    project: Swift.String,
  ) throws -> any AsyncSequence<ResponsePolicy, Swift.Error> {
    let request = ResponsePoliciesClient.ListRequest().with {
      $0.project = project
    }
    return try self.list(byItem: request)
  }

  public func patch(request: ResponsePoliciesClient.PatchRequest) async throws
    -> ResponsePoliciesPatchResponse
  {
    try await self.patch(request: request, options: .init())
  }

  public func patch(
    request: ResponsePoliciesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePoliciesPatchResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func patch(
    project: Swift.String,
    responsePolicy: Swift.String,
    body: ResponsePolicy?,
  ) async throws -> ResponsePoliciesPatchResponse {
    let request = ResponsePoliciesClient.PatchRequest().with {
      $0.project = project
      $0.responsePolicy = responsePolicy
      $0.body = body
    }
    return try await self.patch(request: request)
  }

  public func update(request: ResponsePoliciesClient.UpdateRequest) async throws
    -> ResponsePoliciesUpdateResponse
  {
    try await self.update(request: request, options: .init())
  }

  public func update(
    request: ResponsePoliciesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ResponsePoliciesUpdateResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func update(
    project: Swift.String,
    responsePolicy: Swift.String,
    body: ResponsePolicy?,
  ) async throws -> ResponsePoliciesUpdateResponse {
    let request = ResponsePoliciesClient.UpdateRequest().with {
      $0.project = project
      $0.responsePolicy = responsePolicy
      $0.body = body
    }
    return try await self.update(request: request)
  }
}
