// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

extension ResponsePolicyRulesClient {
  /// Synthetic request message for the [create()][.responsePolicyRules.create] method.
  public struct CreateRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// User assigned name of the Response Policy containing the Response Policy Rule.
    public var responsePolicy: Swift.String = Swift.String()

    /// Synthetic request body field for the [create()][.responsePolicyRules.create] method.
    public var body: ResponsePolicyRule? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CreateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let project = CodingKeys(stringValue: "project")
      static let responsePolicy = CodingKeys(stringValue: "responsePolicy")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "project",
        "responsePolicy",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicy) {
        self.responsePolicy = value
      }
      self.body = try container.decodeIfPresent(ResponsePolicyRule.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.responsePolicy, forKey: .responsePolicy)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.responsePolicyRules.createRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [delete()][.responsePolicyRules.delete] method.
  public struct DeleteRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// User assigned name of the Response Policy containing the Response Policy Rule.
    public var responsePolicy: Swift.String = Swift.String()

    /// User assigned name of the Response Policy Rule addressed by this request.
    public var responsePolicyRule: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DeleteRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeleteRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let project = CodingKeys(stringValue: "project")
      static let responsePolicy = CodingKeys(stringValue: "responsePolicy")
      static let responsePolicyRule = CodingKeys(stringValue: "responsePolicyRule")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "project",
        "responsePolicy",
        "responsePolicyRule",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicy) {
        self.responsePolicy = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicyRule) {
        self.responsePolicyRule = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.responsePolicy, forKey: .responsePolicy)
      try container.encode(self.responsePolicyRule, forKey: .responsePolicyRule)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.responsePolicyRules.deleteRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [get()][.responsePolicyRules.get] method.
  public struct GetRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// User assigned name of the Response Policy containing the Response Policy Rule.
    public var responsePolicy: Swift.String = Swift.String()

    /// User assigned name of the Response Policy Rule addressed by this request.
    public var responsePolicyRule: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GetRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GetRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let project = CodingKeys(stringValue: "project")
      static let responsePolicy = CodingKeys(stringValue: "responsePolicy")
      static let responsePolicyRule = CodingKeys(stringValue: "responsePolicyRule")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "project",
        "responsePolicy",
        "responsePolicyRule",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicy) {
        self.responsePolicy = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicyRule) {
        self.responsePolicyRule = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.responsePolicy, forKey: .responsePolicy)
      try container.encode(self.responsePolicyRule, forKey: .responsePolicyRule)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.responsePolicyRules.getRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [list()][.responsePolicyRules.list] method.
  public struct ListRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Maximum number of results to be returned. If unspecified, the server decides how many results to return.
    public var maxResults: Swift.Int32? = nil

    /// Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
    public var pageToken: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// User assigned name of the Response Policy to list.
    public var responsePolicy: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListRequest().with { $0.maxResults = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let maxResults = CodingKeys(stringValue: "maxResults")
      static let pageToken = CodingKeys(stringValue: "pageToken")
      static let project = CodingKeys(stringValue: "project")
      static let responsePolicy = CodingKeys(stringValue: "responsePolicy")

      static let _knownKeys: Set<Swift.String> = [
        "maxResults",
        "pageToken",
        "project",
        "responsePolicy",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.maxResults = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxResults)
      self.pageToken = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicy) {
        self.responsePolicy = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.maxResults, forKey: .maxResults)
      try container.encodeIfPresent(self.pageToken, forKey: .pageToken)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.responsePolicy, forKey: .responsePolicy)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.responsePolicyRules.listRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [patch()][.responsePolicyRules.patch] method.
  public struct PatchRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// User assigned name of the Response Policy containing the Response Policy Rule.
    public var responsePolicy: Swift.String = Swift.String()

    /// User assigned name of the Response Policy Rule addressed by this request.
    public var responsePolicyRule: Swift.String = Swift.String()

    /// Synthetic request body field for the [patch()][.responsePolicyRules.patch] method.
    public var body: ResponsePolicyRule? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PatchRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PatchRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let project = CodingKeys(stringValue: "project")
      static let responsePolicy = CodingKeys(stringValue: "responsePolicy")
      static let responsePolicyRule = CodingKeys(stringValue: "responsePolicyRule")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "project",
        "responsePolicy",
        "responsePolicyRule",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicy) {
        self.responsePolicy = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicyRule) {
        self.responsePolicyRule = value
      }
      self.body = try container.decodeIfPresent(ResponsePolicyRule.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.responsePolicy, forKey: .responsePolicy)
      try container.encode(self.responsePolicyRule, forKey: .responsePolicyRule)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.responsePolicyRules.patchRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Synthetic request message for the [update()][.responsePolicyRules.update] method.
  public struct UpdateRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    public var clientOperationId: Swift.String? = nil

    /// Identifies the project addressed by this request.
    public var project: Swift.String = Swift.String()

    /// User assigned name of the Response Policy containing the Response Policy Rule.
    public var responsePolicy: Swift.String = Swift.String()

    /// User assigned name of the Response Policy Rule addressed by this request.
    public var responsePolicyRule: Swift.String = Swift.String()

    /// Synthetic request body field for the [update()][.responsePolicyRules.update] method.
    public var body: ResponsePolicyRule? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UpdateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpdateRequest().with { $0.clientOperationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientOperationId = CodingKeys(stringValue: "clientOperationId")
      static let project = CodingKeys(stringValue: "project")
      static let responsePolicy = CodingKeys(stringValue: "responsePolicy")
      static let responsePolicyRule = CodingKeys(stringValue: "responsePolicyRule")
      static let body = CodingKeys(stringValue: "body")

      static let _knownKeys: Set<Swift.String> = [
        "clientOperationId",
        "project",
        "responsePolicy",
        "responsePolicyRule",
        "body",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientOperationId = try container.decodeIfPresent(
        Swift.String.self, forKey: .clientOperationId)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicy) {
        self.responsePolicy = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsePolicyRule) {
        self.responsePolicyRule = value
      }
      self.body = try container.decodeIfPresent(ResponsePolicyRule.self, forKey: .body)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientOperationId, forKey: .clientOperationId)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.responsePolicy, forKey: .responsePolicy)
      try container.encode(self.responsePolicyRule, forKey: .responsePolicyRule)
      try container.encodeIfPresent(self.body, forKey: .body)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/.responsePolicyRules.updateRequest"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
}
