// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ResponsePoliciesStub: Sendable {
    func create(
      request: ResponsePoliciesClient.CreateRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePolicy

    func delete(
      request: ResponsePoliciesClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws

    func `get`(
      request: ResponsePoliciesClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePolicy

    func list(
      request: ResponsePoliciesClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePoliciesListResponse

    func patch(
      request: ResponsePoliciesClient.PatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePoliciesPatchResponse

    func update(
      request: ResponsePoliciesClient.UpdateRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePoliciesUpdateResponse
  }
}
