// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ResponsePoliciesTransport: ResponsePoliciesStub {
    let inner: GoogleGax._HTTPClient

    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      self.inner = try GoogleGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://dns.googleapis.com",
      )
    }

    @concurrent
    public func create(
      request: ResponsePoliciesClient.CreateRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePolicy {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.project as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "project")
          else {
            return nil
          }
          let path = "/dns/v1/projects/\(pathVariable0)/responsePolicies"
          var query = [
            URLQueryItem(name: "$alt", value: "json")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.clientOperationId, prefix: "clientOperationId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.project as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "project",
            expecting: "*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.body {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        ResponsePolicy.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func delete(
      request: ResponsePoliciesClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.project as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "project")
          else {
            return nil
          }
          guard
            let pathVariable1 = try GoogleGax._RoutingMatcher.pathValue(
              request.responsePolicy as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "responsePolicy")
          else {
            return nil
          }
          let path = "/dns/v1/projects/\(pathVariable0)/responsePolicies/\(pathVariable1)"
          var query = [
            URLQueryItem(name: "$alt", value: "json")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.clientOperationId, prefix: "clientOperationId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.project as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "project",
            expecting: "*"
          )
          builder.maybeAdd(
            request.responsePolicy as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "responsePolicy",
            expecting: "*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func `get`(
      request: ResponsePoliciesClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePolicy {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.project as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "project")
          else {
            return nil
          }
          guard
            let pathVariable1 = try GoogleGax._RoutingMatcher.pathValue(
              request.responsePolicy as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "responsePolicy")
          else {
            return nil
          }
          let path = "/dns/v1/projects/\(pathVariable0)/responsePolicies/\(pathVariable1)"
          var query = [
            URLQueryItem(name: "$alt", value: "json")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.clientOperationId, prefix: "clientOperationId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.project as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "project",
            expecting: "*"
          )
          builder.maybeAdd(
            request.responsePolicy as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "responsePolicy",
            expecting: "*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        ResponsePolicy.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func list(
      request: ResponsePoliciesClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePoliciesListResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.project as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "project")
          else {
            return nil
          }
          let path = "/dns/v1/projects/\(pathVariable0)/responsePolicies"
          var query = [
            URLQueryItem(name: "$alt", value: "json")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.maxResults, prefix: "maxResults"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.project as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "project",
            expecting: "*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        ResponsePoliciesListResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func patch(
      request: ResponsePoliciesClient.PatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePoliciesPatchResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.project as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "project")
          else {
            return nil
          }
          guard
            let pathVariable1 = try GoogleGax._RoutingMatcher.pathValue(
              request.responsePolicy as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "responsePolicy")
          else {
            return nil
          }
          let path = "/dns/v1/projects/\(pathVariable0)/responsePolicies/\(pathVariable1)"
          var query = [
            URLQueryItem(name: "$alt", value: "json")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.clientOperationId, prefix: "clientOperationId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.project as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "project",
            expecting: "*"
          )
          builder.maybeAdd(
            request.responsePolicy as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "responsePolicy",
            expecting: "*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.body {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        ResponsePoliciesPatchResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func update(
      request: ResponsePoliciesClient.UpdateRequest, options: GoogleGax.RequestOptions
    ) async throws -> ResponsePoliciesUpdateResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.project as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "project")
          else {
            return nil
          }
          guard
            let pathVariable1 = try GoogleGax._RoutingMatcher.pathValue(
              request.responsePolicy as Swift.String?,
              matching: [.singleWildcard],
              fieldName: "responsePolicy")
          else {
            return nil
          }
          let path = "/dns/v1/projects/\(pathVariable0)/responsePolicies/\(pathVariable1)"
          var query = [
            URLQueryItem(name: "$alt", value: "json")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.clientOperationId, prefix: "clientOperationId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PUT) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.project as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "project",
            expecting: "*"
          )
          builder.maybeAdd(
            request.responsePolicy as Swift.String?,
            matching: [.singleWildcard],
            fieldName: "responsePolicy",
            expecting: "*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.body {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        ResponsePoliciesUpdateResponse.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
