// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Response Policy is a collection of selectors that apply to queries made against one or more Virtual Private Cloud networks.
public struct ResponsePolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// User-provided description for this Response Policy.
  public var description: Swift.String? = nil

  /// The list of Google Kubernetes Engine clusters to which this response policy is applied.
  public var gkeClusters: [ResponsePolicyGKECluster] = []

  /// Unique identifier for the resource; defined by the server (output only).
  public var id: Swift.Int64? = nil

  public var kind: Swift.String? = nil

  /// User labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// List of network names specifying networks to which this policy is applied.
  public var networks: [ResponsePolicyNetwork] = []

  /// User assigned name for this Response Policy.
  public var responsePolicyName: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResponsePolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResponsePolicy().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let description = CodingKeys(stringValue: "description")
    static let gkeClusters = CodingKeys(stringValue: "gkeClusters")
    static let id = CodingKeys(stringValue: "id")
    static let kind = CodingKeys(stringValue: "kind")
    static let labels = CodingKeys(stringValue: "labels")
    static let networks = CodingKeys(stringValue: "networks")
    static let responsePolicyName = CodingKeys(stringValue: "responsePolicyName")

    static let _knownKeys: Set<Swift.String> = [
      "description",
      "gkeClusters",
      "id",
      "kind",
      "labels",
      "networks",
      "responsePolicyName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    if let value = try container.decodeIfPresent(
      [ResponsePolicyGKECluster].self, forKey: .gkeClusters)
    {
      self.gkeClusters = value
    }
    self.id = try container.decodeIfPresent(Swift.Int64.self, forKey: .id)
    self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent([ResponsePolicyNetwork].self, forKey: .networks) {
      self.networks = value
    }
    self.responsePolicyName = try container.decodeIfPresent(
      Swift.String.self, forKey: .responsePolicyName)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encode(self.gkeClusters, forKey: .gkeClusters)
    try container.encodeIfPresent(self.id, forKey: .id)
    try container.encodeIfPresent(self.kind, forKey: .kind)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.networks, forKey: .networks)
    try container.encodeIfPresent(self.responsePolicyName, forKey: .responsePolicyName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.ResponsePolicy"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
