// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configures a RRSetRoutingPolicy such that all queries are responded with the primary_targets if they are healthy. And if all of them are unhealthy, then we fallback to a geo localized policy.
public struct RRSetRoutingPolicyPrimaryBackupPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Backup targets provide a regional failover policy for the otherwise global primary targets. If serving state is set to `BACKUP`, this policy essentially becomes a geo routing policy.
  public var backupGeoTargets: RRSetRoutingPolicyGeoPolicy? = nil

  public var kind: Swift.String? = nil

  /// Endpoints that are health checked before making the routing decision. Unhealthy endpoints are omitted from the results. If all endpoints are unhealthy, we serve a response based on the `backup_geo_targets`.
  public var primaryTargets: RRSetRoutingPolicyHealthCheckTargets? = nil

  /// When serving state is `PRIMARY`, this field provides the option of sending a small percentage of the traffic to the backup targets.
  public var trickleTraffic: Swift.Double? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RRSetRoutingPolicyPrimaryBackupPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RRSetRoutingPolicyPrimaryBackupPolicy().with { $0.backupGeoTargets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupGeoTargets = CodingKeys(stringValue: "backupGeoTargets")
    static let kind = CodingKeys(stringValue: "kind")
    static let primaryTargets = CodingKeys(stringValue: "primaryTargets")
    static let trickleTraffic = CodingKeys(stringValue: "trickleTraffic")

    static let _knownKeys: Set<Swift.String> = [
      "backupGeoTargets",
      "kind",
      "primaryTargets",
      "trickleTraffic",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.backupGeoTargets = try container.decodeIfPresent(
      RRSetRoutingPolicyGeoPolicy.self, forKey: .backupGeoTargets)
    self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
    self.primaryTargets = try container.decodeIfPresent(
      RRSetRoutingPolicyHealthCheckTargets.self, forKey: .primaryTargets)
    self.trickleTraffic = try container.decodeIfPresent(Swift.Double.self, forKey: .trickleTraffic)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.backupGeoTargets, forKey: .backupGeoTargets)
    try container.encodeIfPresent(self.kind, forKey: .kind)
    try container.encodeIfPresent(self.primaryTargets, forKey: .primaryTargets)
    try container.encodeIfPresent(self.trickleTraffic, forKey: .trickleTraffic)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.RRSetRoutingPolicyPrimaryBackupPolicy"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
