// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration for an individual load balancer to health check.
public struct RRSetRoutingPolicyLoadBalancerTarget: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The frontend IP address of the load balancer to health check.
  public var ipAddress: Swift.String? = nil

  /// The protocol of the load balancer to health check.
  public var ipProtocol: RRSetRoutingPolicyLoadBalancerTarget.IpProtocol? = nil

  public var kind: Swift.String? = nil

  /// The type of load balancer specified by this target. This value must match the configuration of the load balancer located at the LoadBalancerTarget's IP address, port, and region. Use the following: - *regionalL4ilb*: for a regional internal passthrough Network Load Balancer. - *regionalL7ilb*: for a regional internal Application Load Balancer. - *globalL7ilb*: for a global internal Application Load Balancer.
  public var loadBalancerType: RRSetRoutingPolicyLoadBalancerTarget.LoadBalancerType? = nil

  /// The fully qualified URL of the network that the load balancer is attached to. This should be formatted like `https://www.googleapis.com/compute/v1/projects/{project}/global/networks/{network}`.
  public var networkUrl: Swift.String? = nil

  /// The configured port of the load balancer.
  public var port: Swift.String? = nil

  /// The project ID in which the load balancer is located.
  public var project: Swift.String? = nil

  /// The region in which the load balancer is located.
  public var region: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RRSetRoutingPolicyLoadBalancerTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RRSetRoutingPolicyLoadBalancerTarget().with { $0.ipAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ipAddress = CodingKeys(stringValue: "ipAddress")
    static let ipProtocol = CodingKeys(stringValue: "ipProtocol")
    static let kind = CodingKeys(stringValue: "kind")
    static let loadBalancerType = CodingKeys(stringValue: "loadBalancerType")
    static let networkUrl = CodingKeys(stringValue: "networkUrl")
    static let port = CodingKeys(stringValue: "port")
    static let project = CodingKeys(stringValue: "project")
    static let region = CodingKeys(stringValue: "region")

    static let _knownKeys: Set<Swift.String> = [
      "ipAddress",
      "ipProtocol",
      "kind",
      "loadBalancerType",
      "networkUrl",
      "port",
      "project",
      "region",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.ipAddress = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress)
    self.ipProtocol = try container.decodeIfPresent(
      RRSetRoutingPolicyLoadBalancerTarget.IpProtocol.self, forKey: .ipProtocol)
    self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
    self.loadBalancerType = try container.decodeIfPresent(
      RRSetRoutingPolicyLoadBalancerTarget.LoadBalancerType.self, forKey: .loadBalancerType)
    self.networkUrl = try container.decodeIfPresent(Swift.String.self, forKey: .networkUrl)
    self.port = try container.decodeIfPresent(Swift.String.self, forKey: .port)
    self.project = try container.decodeIfPresent(Swift.String.self, forKey: .project)
    self.region = try container.decodeIfPresent(Swift.String.self, forKey: .region)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.ipAddress, forKey: .ipAddress)
    try container.encodeIfPresent(self.ipProtocol, forKey: .ipProtocol)
    try container.encodeIfPresent(self.kind, forKey: .kind)
    try container.encodeIfPresent(self.loadBalancerType, forKey: .loadBalancerType)
    try container.encodeIfPresent(self.networkUrl, forKey: .networkUrl)
    try container.encodeIfPresent(self.port, forKey: .port)
    try container.encodeIfPresent(self.project, forKey: .project)
    try container.encodeIfPresent(self.region, forKey: .region)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The enumerated type for the [ipProtocol][.RRSetRoutingPolicyLoadBalancerTarget.ipProtocol] field.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum IpProtocol: Codable, Equatable, Sendable {
    case undefined
    /// Indicates the load balancer is accessible via TCP.
    case tcp
    /// Indicates the load balancer is accessible via UDP.
    case udp
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(Swift.String)

    /// Returns the string value (or name) associated with the enumeration.
    public var stringValue: Swift.String? {
      switch self {
      case .undefined: return "undefined"
      case .tcp: return "tcp"
      case .udp: return "udp"
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IpProtocol/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "undefined": self = .undefined
      case "tcp": self = .tcp
      case "udp": self = .udp
      default: self = .unknownStringValue(stringValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      let s = try container.decode(Swift.String.self)
      self.init(stringValue: s)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .undefined: return try container.encode("undefined")
      case .tcp: return try container.encode("tcp")
      case .udp: return try container.encode("udp")
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The enumerated type for the [loadBalancerType][.RRSetRoutingPolicyLoadBalancerTarget.loadBalancerType] field.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum LoadBalancerType: Codable, Equatable, Sendable {
    case `none`
    /// Indicates the load balancer is a Cross-Region Application Load Balancer.
    case globalL7Ilb
    /// Indicates the load balancer is a Regional Network Passthrough Load Balancer.
    case regionalL4Ilb
    /// Indicates the load balancer is a Regional Application Load Balancer.
    case regionalL7Ilb
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(Swift.String)

    /// Returns the string value (or name) associated with the enumeration.
    public var stringValue: Swift.String? {
      switch self {
      case .`none`: return "none"
      case .globalL7Ilb: return "globalL7ilb"
      case .regionalL4Ilb: return "regionalL4ilb"
      case .regionalL7Ilb: return "regionalL7ilb"
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LoadBalancerType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "none": self = .`none`
      case "globalL7ilb": self = .globalL7Ilb
      case "regionalL4ilb": self = .regionalL4Ilb
      case "regionalL7ilb": self = .regionalL7Ilb
      default: self = .unknownStringValue(stringValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      let s = try container.decode(Swift.String.self)
      self.init(stringValue: s)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .`none`: return try container.encode("none")
      case .globalL7Ilb: return try container.encode("globalL7ilb")
      case .regionalL4Ilb: return try container.encode("regionalL4ilb")
      case .regionalL7Ilb: return try container.encode("regionalL7ilb")
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/.RRSetRoutingPolicyLoadBalancerTarget"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
